Add CSRF support to uploader Component
DSpace/dspace-angular pull request #1024
Opened 2021-02-17 22:19 UTC by tdonohue

## References
* Fixes #1023 
* Relates to #977  

## Description
As noted in #1023, after merging PR #977 to add CSRF protection, all file uploads are failing with a `403 Forbidden: Access is denied. Invalid CSRF token.` error.

The reason for this error is that our current upload library (`ng2-file-upload`) doesn't currently support Angular Http Interceptors (like our `xsrf.interceptor.ts` which manages CSRF/XSRF tokens for all parts of our Angular app).  This is a known issue in `ng2-file-upload` for many years and described in more detail at https://github.com/valor-software/ng2-file-upload/issues/950

I've solved this issue in our `Uploader` component by _temporarily_ duplicating much of the logic of our `xsrf.interceptor.ts` into the `uploader.component.ts`.  This includes the following logic:

* Added logic to ensure `uploader.component.ts` sends the XSRF token in every upload request (same logic as  `xsrf.interceptor.ts`)
* Added logic to `uploader.component.ts` to check for changes to XSRF token & ensure it gets saved to a cookie (same logic as  `xsrf.interceptor.ts`)
* Updated `uploader.component.ts` to ensure it always uses `withCredentials = true` (as this is needed to ensure it passes back cookies related to XSRF/CSRF). (also same logic as  `xsrf.interceptor.ts`)

## Instructions for Reviewers

List of changes in this PR:
* Test that uploading files now works.  For example, start a new submission and drag & drop a file
* Test that an action *after* an upload also works (this tests that we are getting the new CSRF token after a successful upload).  For example, delete the uploaded file from the item.

2021-02-26 18:40 UTC, tdonohue commented
@artlowel : I've flagged this as `high priority`, as this is getting in the way of **all uploads** to DSpace 7.  If you (or someone on your team) can find time to look at this on Monday, I'd appreciate it.  I'd like to find a way to get this moved forward soon.

2021-03-01 09:31 UTC, artlowel requested changes
Thanks @tdonohue!

The code looks good, and I can upload files from the submission most of the time. But I still get seemingly random CSRF errors if I upload files, remove them, or discard the submission. I haven't found a consistent way to reproduce the errors. However they seem to occur more frequently when I save an in progress submission, and then edit it again. Uploading multiple files in quick succession also seems to increase the chances of an error.

Both the successful and failed requests have X-XSRF-TOKEN headers. However successive failed requests all seem to have the same X-XSRF-TOKEN header, while successive succeeded requests all have different values.

2021-03-01 22:53 UTC, tdonohue commented
@artlowel : Good catch.  This was a hard one to debug, as I was having trouble reproducing it when using a local REST API.  However, once I switched to using the **demo REST API**, I was able to find similar behavior...

Here's the way I was able to semi-reliably reproduce the error on the demo REST API:
1. Start a submission, make some small edits. Click "Save for later"
2. Go back into that same submission.
3. As the **first action**, immediately drag & drop. ~5 files (at the same time) into the submission.  In that scenario, the first file uploads successfully, while the others fail with CSRF errors. 

For some strange reason, I wasn't able to see that same failure when using a local REST API.

Nonetheless, after some closer analysis of the code in `ng2-file-upload` library, I realized that the `onBeforeUploadItem()` method does NOT seem to _always_ be called prior to uploading **queued items** (several in a row).  Previously, I had assumed this was called between each queued item, but it doesn't seem to be the case (it might be a bug in the library, but we can work around it for now). 

So, I've pushed up a small fix to also "reset" our CSRF request header in `onCompleteItem()` and `onErrorItem()` as those are always called after each file is uploaded -- so if the upload results in a new CSRF Token, I can use that response to prepare the headers for the next file in the queue.

This small change seems to work!  I've retested with the demo REST API and local REST API and cannot reproduce those issues anymore.  Could you give this updated PR another try?

2021-03-02 18:36 UTC, tdonohue commented
@artlowel : Just a note... based on your feedback, I've also created a small PR on the REST API to change how frequently the CSRF Token is reset/refreshed.  I've noticed myself in testing this PR that it's currently reset on every request, which means sending many requests in a row (like doing multiple uploads in a row quickly) run the risk of occasional "race conditions".  I'm not yet sure if that also could be what you saw...but I think there's a definite risk to changing this token too frequently.   So, here's that PR: https://github.com/DSpace/DSpace/pull/3168/

In any case, I think this REST API PR is only loosely related to this Upload component fix.  The two PRs together should be more "stable" (less likely to see random CSRF issues), but they can be merged/reviewed separately.

2021-03-03 15:01 UTC, artlowel approved these changes
Thanks @tdonohue!

I can no longer reproduce the issue

2021-03-03 17:26 UTC, merged