Cst 3782 fix repeatable fields
DSpace/dspace-angular pull request #1025
Opened 2021-02-18 11:42 UTC by alemarte

## References
Related to #971 

## Description
This PR aims to remove the template row from the repeatable field control, in order to tackle numerous side effects that have arisen with such an implementation.

Most of the changes consists in reverting to the previous beheviour of the form array control. 
Then the lookup functionality have been extrapolated from the form container (which should have very bounded responsibilities) to the customization of repeatable fields in the form component.

## Instructions for Reviewers

Summarizing the results of this PR, we can make the following considerations:

1. We have the possibility to increment the numbers of the repeatable field values, by clicking on the Add More button.

2. We can delete values by clicking on the Trash button.

3. We can drag and drop values in order to sort them.

4. Since we don't have anymore the fake template row on the top of the control, this solution doesn't allow the user to direct inject the query text into the lookup modal.
In our opinion clicking on the Lookup button and then write the text criteria inside the modal brings us to a very similar experience and so it could be a very good compromise.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

2021-02-19 23:06 UTC, tdonohue requested changes
@alemarte : I gave this a quick test today, and it seems to work (I'll admit, I only tried the basics so far though & need to do a more thorough test next week).  I did notice a few small usability issues that I think we should clean up;

1. The "hint" text always appears under the *first* repeatable field, which looks odd to me.  I think it should appear under the *last* repeatable field, in the same way that the "+ Add more" button always appears at the end of the list.
2. When dragging the last item, when you grab the item, it "appears" as though you are also dragging the "+ Add more" button.  This is a minor issue, as the "+ Add more" button doesn't move after reordering...it just looks odd

I also noticed one small misspelling in the new code.  Overall though, this looks good at a glance.  I admit, I haven't yet tried the "Lookup" feature again though -- will do so next week.

**UPDATE:**  I tested the "Lookup" feature today (Monday, Feb 22).  It mostly works, but I've found a few issues:
1. As detailed in the original ticket, we had talked about having the "Lookup" feature appear _next to each value_ in a multi-valued field: https://github.com/DSpace/dspace-angular/issues/971#issuecomment-747546143   Currently, it's just appearing a the bottom of the list, which limits you to only doing a "Lookup" of the *last* value in the list.
2. Clicking "Lookup" does bring the value into the lookup popup so that I can search on it.  That works.  However, once I select a value in the popup, I end up with an error: 
`Unable to add relationship: No suitable match could be found for relationship type isAuthorOfPublication between the two items`   But, I think this might be an existing error (i.e. may not be a fault of this PR), as I cannot seem to get this "Lookup" popup working on the demo site either.  So, we could log this as a separate bug, unless you figure out an easy way to fix it.

**UPDATE #2:** Some more issues I just found:

3. This appears to have **broken** the "Subject Keywords" field.  I no longer can add keywords by pressing "Enter"

2021-02-23 16:21 UTC, tdonohue reviewed
@alemarte : Just a note, I updated my review above with further tests yesterday.  Overall, this is looking good...just some (hopefully minor) things to clean up (see above).

2021-02-24 16:06 UTC, alemarte commented
@tdonohue I've addressed for now the questions about styling (hint and drag and drop). And fixed the remaining bug of https://github.com/DSpace/dspace-angular/issues/950
Add and delete operations seem to work well. The bug I found was related to the drag and drop event that was not handled properly for the qualdrop model. 

_A side note:_
About the https://github.com/DSpace/dspace-angular/issues/950 I noticed while testing the submission form that a 403 error occurs very often.

2021-02-25 16:29 UTC, atarix83 commented
@tdonohue 
> UPDATE: I tested the "Lookup" feature today (Monday, Feb 22). It mostly works, but I've found a few issues:
 As detailed in the original ticket, we had talked about having the "Lookup" feature appear next to each value in a multi-valued field: #971 (comment) Currently, it's just appearing a the bottom of the list, which limits you to only doing a "Lookup" of the last value in the list.

I've applied changes to address what we decided in the original ticket

> Clicking "Lookup" does bring the value into the lookup popup so that I can search on it. That works. However, once I select a value in the popup, I end up with an error:
    Unable to add relationship: No suitable match could be found for relationship type isAuthorOfPublication between the two items But, I think this might be an existing error (i.e. may not be a fault of this PR), as I cannot seem to get this "Lookup" popup working on the demo site either. So, we could log this as a separate bug, unless you figure out an easy way to fix it.

I see that this error occurs also on the current demo if you try to submit to `3-step Workflow collection`

2021-03-02 22:59 UTC, tdonohue requested changes
@alemarte and @atarix83 : I've retested today, and I'm getting **very odd** behaviors when reordering newly added values.  It seems like several PATCH commands are queued up and sent back to back, causing an odd list of values.

Here's how I can reproduce it:
1. Start with a Submission with zero or one Author.
2. Add three authors to it. Then (without saving), reorder them several times in a row. 
3. Then click "Save for Later".  In Chrome DevTools, I see a PATCH request send with a large number of "add" commands. Sometimes this step will succeed , and other times it will fail.
4. Go back into the Item and it may now have an unexpected author listing.  When I did this I saved with 4 authors and came back in to find 8 (with all of them appearing twice).

A few other minor issues:
* As discussed in the ticket, the "Lookup" button should be a 🔎 icon instead of the text "Lookup"
* Clicking "Lookup" next to a value immediately clears that value.  This is unexpected, as if I close the popup )without selecting anything) the old value is now gone.
* I've also run into issue #1020 while testing this PR.  However, this appears to be a separate issue (which is reproducible also on `main`)

2021-03-04 17:33 UTC, alemarte commented
@tdonohue There were a missing part about the handling of the move operation. It has been integrated in the latest two commits.

2021-03-05 19:15 UTC, tdonohue requested changes
@alemarte : I tested this again today.  It's looking better overall. The reordering is now working properly, but I see some issues I reported earlier still remain.

The issues that I still can reproduce are the following:
* As discussed in the ticket, the "Lookup" button should be a 🔎 icon instead of the text "Lookup"
* Clicking "Lookup" next to a value immediately clears that value (it sends a PATCH with remove). This is unexpected, as if I close the popup (without selecting anything) the old value is now gone.  The value also does *not* get copied into the Lookup popup window, so clicking Lookup is deleting it with no replacement. 
    * If I enter two authors first, then click Lookup on the first author (clearing it's value), close the window, then click Lookup on the second value...I get a 500 error. The form then becomes unusable until I reload the entire page...every action from that point throws a 500 error.
* Bug #1020 still exists, but we can fix that in a followup PR if you'd rather.

Overall though, as mentioned, this is working much much better overall. It's harder to find errors now, but still a few remain.  Thanks!

2021-03-10 17:56 UTC, alemarte commented
@tdonohue the lookup button has been modified with a search icon.
About the lookup click which clears the field, this is the current demo behavior and fix this would require further investigation and a non trivial implementation.

When you click on the Lookup button the modal is launched (hopefully with the search field populated with the plain value stored on the repeatable item). Inside the modal the user is completely free to operate: he could close without operations, he could select several items but also remove existing ones. There is no an easy way to intercept whether the original item has to be removed or not. Furthermore, the current behavior appends new selected items at the end of the array, so even the position wouldn't be correct.

For now I've commented out the part of the logic responsible to delete the item when opening the modal. I'm afraid that the only easy fix to this is to manually remove the stale plain record. The better solution would involve a deep rethinking of the component responsible to manage the content of the lookup modal.

2021-03-10 23:03 UTC, tdonohue commented
@alemarte : Apologies, but it looks like this PR has a minor code conflict now.  Could you rebase this on `main` to resolve it?

2021-03-17 17:02 UTC, tdonohue approved these changes
👍 Thanks @alemarte .  I retested this today, and the issues I previous reported are now resolved.  So, I feel this is good enough to merge.

That said, I did want to note that I've noticed two new bugs in the Submission UI, but I don't think either of these are directly related to this PR.  So, they could be logged & fixed separately as needed (unless you know of a quick fix & want to implement it).

1. The first issue is that creating & linking Entities via the "Lookup" option (e.g. next to the Author field) no longer seems to work.  This is related to what [you described in your comment](https://github.com/DSpace/dspace-angular/pull/1025#issuecomment-795824009).  Simply put, if you click Lookup, select an Author via ORCID, and select to create a new Entity, the process claims to succeed...but that Author record doesn't appear under the Author field in the Submission UI.  However, this same issue occurs on the Demo Site (https://demo7.dspace.org/), so it doesn't seem to be caused by this PR & probably should be logged as a separate ticket (**I can add a new ticket assuming others agree**)
2. The other issue is with the "Subject Keywords" field.  I can verify that #1020 is now fixed...however, it appears we no longer can add Keyword which are **not** in a Controlled Vocabulary.  If I select an entry from the Controlled Vocabulary, then I see that Keyword added.  But, there seems to be no way to add other keywords -- I expected to be able to type a word and click Enter (or similar) and see them also be added.  But again I'm not sure if this is caused by this PR, and it could be fixed in a follow-up as needed (**I can add a new ticket assuming others agree**)

2021-03-23 17:11 UTC, artlowel requested changes
Thanks @alemarte! 
The code looks good, and the feature works well 👍

I did notice a few issues though, most having to do with fields that mix entities and metadata values.

All tests were performed in prod mode, in [this collection](http://localhost:4000/submit?collection=dd1240ae-d7dd-405c-bdc3-d6c960609433) on the api7.dspace.org backend. All tests use the author field, unless mentioned otherwise.

#### Alert while dragging
When you pick up a row in this PR to drag it, it changes into an alert that says "Drop the item in a new postion". That didn't use to be the case. You used to simply see the row you were holding as it was. 

Having the thing you picked up change as you drag it is disorientating in my opinion. 

#### Search query stored as metadata value
If you enter a search query and click the lookup button, and then select an entity and create a relationship, the field with the search query disappears and the save button becomes active.

If you save, the field with the query reappears and seems to have been stored as metadata on the item

#### Saving empty field issue
If you enter a value in a repeatable field, then click "add more", the save button is disabled: it hasn't detected any changes. So far, so good.
 
However if you drag that empty field to the top, without filling it in, the save button becomes active, and if you click save you get an error. (even if you've also made other changes that aren't just empty fields)


#### Subject Keywords unclickable
The subject keywords field can't be clicked (to start typing in it) most of the time. You can however select a different field and tab to it, to select it

#### Reordering in the identifiers field is confusing
Because the identifiers fields are all in a single reorderable list I got the impression reordering wasn't working at first.

On closer inspection it seems that the values for each kind of identifier (ISSN, Uri, Other, etc) _do_ retain their order, but you're also free to mix different kinds of identifiers. You lose that mixed order if you reload the edit page.

The order between values of e.g. dc.identifier.issn and dc.identifier.other are of course meaningless, there's no need to store them, but the UI makes it seem like you can.

It would be better if each type of identifier had its own reorderable section, and they couldn't be mixed.

#### Missing hint
If an entity is the bottom value of a repeatable field, the hint isn't shown. It will reappear if you drag a metadata value to the bottom.
 
 
#### Indent
Repeatable fields are ever so slightly more indented than other fields, which makes the form look untidy
 
![Screen Shot 2021-03-23 at 17 31 35](https://user-images.githubusercontent.com/1567693/112188202-1466bd00-8c03-11eb-8a3b-0d00c184a356.png)

2021-04-01 15:55 UTC, artlowel approved these changes
Thanks @alemarte!

> #### Alert while dragging

>We opted to generalize the drag and drop placeholder because with the new repeatable fields implementation the old display strategy appeared to be even weirder, since together with the field value the lookup button and the add-more button were dragged too.
>To experiment the effect just comment out the [*cdkDragPreview](https://github.com/DSpace/dspace-angular/blob/08afa4723b2c28ac9a9d3daeb217d234e2f64aab/src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html#L17). Since we are operating at the outer array level, we don't have an easy way to create a preview which contains the dragged value in a sufficient generalized manner, suitable for all the possible models. We can of course manage that, but we are running out of time and restoring this could easily be a following up improvement.

I think it works more intuitively without the cdkDragPreview template. You can hide the buttons and the hints while dragging by specifying a `cdkDragPreviewClass` and setting buttons and hints to `display: none`. I've done so in this commit: https://github.com/atmire/dspace-angular/commit/a1884b5b71f0ac941165e8091e46aed5cbf3b2e1

One less than ideal thing about that is that you have to do it in the global css as this spans multiple components, but I don't think that's a big problem if the css class is specific enough.


> #### Saving empty field issue
>This turned out to be a very big problem. This problem is also present on the demo, and is mainly due to the fact the the move operation only sees the current form status, without considering possible empty values in the middle. A way to simply prove that is by loading a submission starting with 3 saved author. Then:
>1) empty the author in the middle
>2) drag the last author to any other position
>3) save
>
>The move operation wrongly sees the array length as 3, but the previous patch reduced to 2.
>Fixing this by tuning the patch move operation generator is sincerely a world of pain. We don't have a way to monitor and predict the user behavior and there are too many cases to handle.
>So we change approach. We tried to apply a much simpler approach by patching every time the value of the entire array. It works, smoothly 100% of the time.
>As a side note about patching the entire array, we found out that it doesn't work when at least virtual value is present. So this will need a fix rest side. (already estimated to 8h-12h, and we could claim the task after beta5 during the testhaton).

I agree patching the entire array is the better solution. ~However breaking this virtual values in repeatable fields right before testaton might not be the best plan either. So perhaps we should rollback this fix for now, work on the backend during testathon, and release this fix as a separate PR when the rest work is done too. @tdonohue, what do you think?~ 

We discussed this in today's meeting @abollini will ensure that the Rest PR is ready before testathon.

> #### Reordering in the identifiers field is confusing
>This is weird I agree, but is the current demo behaviour and in the context of this PR we have two choices in my opinion. Enable the dragging as is or disable it completely for the qualdrop scenario. I've added a configuration field to the DynamicRowArrayModel that allows us to conveniently disable the drag and drop feature and exploited it for cases such as the identifier form control. [See](https://github.com/DSpace/dspace-angular/blob/08afa4723b2c28ac9a9d3daeb217d234e2f64aab/src/app/shared/form/builder/parsers/field-parser.ts#L55) here

I wouldn't disable it, I'd just create a ticket for it and come up with a better approach for this either during testathon or when we work on the submission for 7.1

2021-04-01 18:04 UTC, atarix83 commented
@artlowel 
> I think it works more intuitively without the cdkDragPreview template. You can hide the buttons and the hints while dragging by specifying a cdkDragPreviewClass and setting buttons and hints to display: none. I've done so in this commit: atmire@a1884b5

done

2021-04-01 18:53 UTC, tdonohue commented
Merging, as this is now at +2.  Thanks @alemarte and @atarix83 !

2021-04-01 18:53 UTC, merged