Submission dropzone issues
DSpace/dspace-angular pull request #1053
Opened 2021-03-12 10:40 UTC by LotteHofstede

## References
* Fixes #957 and #849

## Description
- The dropzone on the submission form will no longer be rendered when the submission form does not include an upload section.
- When a file is dropped on the submission forms dropzone, the page will not automatically scroll to the top of the age anymore. The dropzone and its progress bar is now always visible at the top of the page, similar to the collection dropdown.  

## Instructions for Reviewers
- Collections without an upload section in their form definition, should no longer show the dropzone on their submission page
- Dropping a file anywhere on the submission page should no longer cause the page to scroll up, but should always show the progress bar at the top of the page, independently from the user's current scroll position.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

2021-03-31 13:57 UTC, atarix83 requested changes
thanks @LotteHofstede for the PR. I've tested and it seems to work properly. However I have a suggestion on implementation which it would be nice to be implemented

2021-03-31 13:57 UTC, atarix83 commented on src/app/submission/form/submission-form.component.ts
> +          this.uploadEnabled$.next(isNotEmpty(sectionList) && sectionList.some(config => config.sectionType === SectionsType.Upload));
In my opinion a cleanest way to find out if the upload section is available is to use the [sections.service](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/sections.service.ts). it includes a [method to check the availability of a section by given id](https://github.com/DSpace/dspace-angular/blob/ea3886bbfa63d8bc41664f3d76d0534863faceac/src/app/submission/sections/sections.service.ts#L303-L310). It'd would be nice to have a similar method that use the section type to check if any sections with the given type are available

2021-04-01 22:02 UTC, tdonohue approved these changes
👍 Looks good to me & tested and it works.

I've also verified that @atarix83's feedback was addressed in this PR, using the recommended method he linked to.

2021-04-02 13:34 UTC, atarix83 approved these changes
@LotteHofstede the changes you made is not exactly what I meant. Indeed using the `isSectionAvailable` to check if upload section is available works only because by rest configuration currently the upload section's type and the id are the same : 
``` 
        <step-definition id="upload">
            <heading>submit.progressbar.upload</heading>
            <processing-class>org.dspace.app.rest.submit.step.UploadStep</processing-class>
            <type>upload</type>
        </step-definition>
```
A better solution is to create a similar method that search by section type, so we would be safe id the id will be changed. I've applied this change [with this commit](https://github.com/4Science/dspace-angular/commit/d28e9c5c2fb1c4841261fd73c02512a2fc5146c0).
 @tdonohue My suggestion is to pick it up and to merge this PR after a quick review

2021-04-02 14:17 UTC, LotteHofstede commented
@atarix83 Thanks for the feedback. You're absolutely right, I'm sorry I missed that. I cherry-picked your changes into this branch and pushed them.

2021-04-02 15:19 UTC, tdonohue commented
Merging, as this is at +2 & @atarix83's improvement commit was included. Thanks again @LotteHofstede (and @atarix83) !

2021-04-02 15:19 UTC, merged

2021-04-02 21:43 UTC, tdonohue commented
Unfortunately, after merging this I've just now realized it's had major side effects. It's now impossible to click on any field in the submission form, which means it's impossible to submit a new item.  I've created a revert PR #1083 which I'll merge shortly just to get the demo site working again.

2021-04-06 11:10 UTC, LotteHofstede commented
@tdonohue That's indeed unfortunate, my apologies for not noticing this very obvious issue.

It should be fixed now that the page-wide dropzone is only rendered once the user actually drags a file onto the window.

I created a new PR https://github.com/DSpace/dspace-angular/pull/1087