Ensure we are always using UTC dates in the UI, as the backend expects/uses UTC-based dates
DSpace/dspace-angular pull request #1262
Opened 2021-07-01 22:22 UTC by tdonohue

## References
* Fixes #1256

## Description
In several areas of the UI (especially related to embargo dates) we use localized versions of dates (e.g. `getFullYear()`, `getMonth()`, `getDate()`).  This causes odd behavior when using the UI from a location with a vastly different time than UTC, and results in the UI sometimes accidentally changing embargo dates, etc.

This PR fixes those issues by ensuring we are always using UTC dates when interacting with Typescript `Date` object.  While the main bug is with the embargo date, I decided to do a find & replace on these methods, as I expect odd behavior would occur elsewhere as well.

2021-07-01 22:23 UTC, tdonohue commented
@atarix83 and @artlowel : I assigned both of you, but likely only one needs to do a thorough review.

2021-07-08 13:26 UTC, atarix83 requested changes
thanks @tdonohue for this PR

unfortunately now I have the same issue you have while editing embargo date within the submission. If I change the date, a date two days earlier than the selected date is saved.

After investigating on the problem, I think I've found the solution. 
if you replace the [following line ](https://github.com/DSpace/dspace-angular/pull/1262/files#diff-9b2cd9b7b3d7459c589139375b5f215eb67129d213e080966aa86f349cd79922L60) 
with the following code 
```
return new Date(Date.UTC(date.year, (date.month - 1), date.day));
``` 
the issue is resolved and all should work properly

2021-07-12 17:26 UTC, tdonohue commented
@atarix83 : I've made the update you suggested, please re-test when you get a chance.  I've tested on my end again, and this PR works great for me.  That said, I'd appreciate it if you could check from your timezone again.

2021-07-13 07:14 UTC, atarix83 approved these changes
thanks @tdonohue 

it works properly now

2021-07-13 14:06 UTC, merged