[CST-5674] Edit resource policy
DSpace/dspace-angular pull request #1641
Opened 2022-05-05 14:25 UTC by davide-negretti

## References
* Fixes #1585
* Requires DSpace/DSpace#8285
* Requires DSpace/DSpace#8287

## Description
It is now possible to change the **policy type**, the **action type** and the **target** (ePerson or group) of a resource policy.

![image](https://user-images.githubusercontent.com/87638927/166944081-dc5aa4e9-5855-4fe0-a23a-700cb2120806.png)

## Important warnings

* **Due to a pre-existing bug the new policy target will not be visible in the **Edit bitstream's Policies** page (a page refresh is needed).**  
#644
* When the form is submitted, two separate HTTP requests are done: a PATCH for the policy details and a POST for the new policy target. It may happen that one request fails while the other one doesn't. In case of error, the notification will inform the user about the specific errors that have occurred.

## Instructions for Reviewers

List of changes in this PR:
* Policy type, action type and target fields were previously enabled only when a new policy was being created. They are now enabled also when an existing policy is being edited. 
* An `updateTarget()` method has been implemented to update the policy target

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

2022-05-06 13:46 UTC, corrad82-4s requested changes
I have tested this PR, together with its rest counterpart, and all seems fine to me.
I'd just fix the alerts raised by LGTM engine, and check why there's a failing test just with node 12, whereas all tests are passing with node 14.

2022-05-06 14:54 UTC, tdonohue commented
@davide-negretti and @corrad82-4s : When a test fails _only on_ Node 12 or _only on_ Node 14, that is **usually** a sign that a random hiccup occurred.  In this case, the Node 12 tests look like they couldn't run because headless Chrome failed to start in our CI environment.  So, I restarted the Node 12 tests a moment ago & I'd expect they probably will succeed this time around.

2022-05-09 15:47 UTC, corrad82-4s approved these changes
Hi,
since we have clarified the issue occurring with node 12 tests, and lgtm reports have been solved. This PR looks good to me

2022-05-13 19:37 UTC, abollini requested changes
changes are required due to the rest contract feedback, see https://github.com/DSpace/RestContract/pull/193

2022-05-13 19:37 UTC, abollini commented on src/app/core/resource-policy/resource-policy.service.ts
> +      const request = new PostRequest(requestId, resourceEndpoint, targetEndpoint, options);
you need to switch to a PUT request, see comments in the rest contract

2022-05-17 14:39 UTC, davide-negretti commented
@abollini @corrad82-4s @tdonohue code has been updated according to the changes to the REST contract

2022-05-18 15:47 UTC, tdonohue requested changes
@davide-negretti : Overall the code looks good & it works.  However, I'm seeing a (possible caching) issue immediately after I update any policy. Here's what I'm doing:

1. First, I'm running this in production mode (`yarn build:prod; yarn serve:ssr`)
2. Edit an existing Item. Go to its Authorization policies
3. Find the "Anonymous READ" policy for the Item.  Edit it, and change to "Administrator" group.  Click save.  
4. Update is successful, but when I'm sent back to the list of policies, the READ policy has no Group listed (see screenshot). 
5. If I reload the page (click reload in browser), it updates and shows "Administrator" group correctly.
![missing-group](https://user-images.githubusercontent.com/483997/169085833-6d113199-cb3c-4c29-808a-8cb28d479b2a.png)

Beyond that strange caching issue, the functionality works.  I also have an inline comment below where it looks like we might be missing new tests.  If it's possible to add those easily, I'd appreciate it.

2022-05-18 15:47 UTC, tdonohue commented on src/app/core/resource-policy/resource-policy.service.ts
> +  updateTarget(resourcePolicyId: string, resourcePolicyHref: string, uuid: string, type: string): Observable<RemoteData<any>> {
I'm not seeing new tests in `resource-policy.service.spec.ts` that correspond to this new method.  Could we add tests for it?

2022-05-18 21:45 UTC, davide-negretti commented
@tdonohue 
> Overall the code looks good & it works. However, I'm seeing a (possible caching) issue immediately after I update any policy
This is a known issue that has already been reported two years ago, see "Important warnings" in the original PR comment for the original GitHub issue.

> Beyond that strange caching issue, the functionality works. I also have an inline comment below where it looks like we might be missing new tests. If it's possible to add those easily, I'd appreciate it.
Ok, I will try to add some coverage

2022-05-19 10:02 UTC, davide-negretti commented
@tdonohue I suggest to test this again after having merged #1608, it is possible that this will solve the caching issue

2022-05-20 14:46 UTC, davide-negretti commented
@tdonohue I added a new test case for `updateTarget` method

2022-05-25 19:31 UTC, tdonohue approved these changes
👍 Thanks @davide-negretti !  Re-tested / re-reviewed today, and this looks good enough for me.  I can still reproduce the caching issue caused by #644 which I described in [my prior review](https://github.com/DSpace/dspace-angular/pull/1641#pullrequestreview-977195916).  But, that doesn't seem to be the fault of this PR.  So, I'll go ahead and approve this PR & merge it -- and I flagged #644 as `high priority` so that hopefully we can find a solution in 7.4

(Side note: I also verified that #741 does NOT solve this specific caching issue... though that PR is also beneficial, this caching bug is a different issue it seems.)

2022-05-25 19:33 UTC, tdonohue commented
Merging with +3

2022-05-25 19:33 UTC, merged