Ensure auth methods are re-fetched after an authentication error.
DSpace/dspace-angular pull request #1799
Opened 2022-08-29 08:20 UTC by philipprumpf

## References
* Fixes #1793.

## Description
Make sure a `CheckAuthenticationTokenAction` is triggered if authentication fails (this happens when the backend is restarted while a non-expired token is in storage). This, in turn, refreshes the auth methods and avoids an empty non-functional authentication menu.

## Instructions for Reviewers
We must be careful not to trigger a `CheckAuthenticationTokenAction` recursively, which is why `hasToken` was added.

List of changes in this PR:
* add `AuthenticationService.hasToken` to check existence of a token
* make `removeToken` call conditional on the existence of a token
* trigger `CheckAuthenticationTokenAction` if authentication fails and there was a valid-looking token

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [X] My PR doesn't introduce circular dependencies
- [X] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

2022-08-29 14:31 UTC, tdonohue reviewed
@philipprumpf : Thanks!  I've added a brief comment inline about how to add one simple test.  I'm also uncertain of the best way of adding a test for `auth.effects.ts` (I do see there's an `auth.effects.spec.ts` -- I'm just less familiar with its test structure).  So, I'll assign this to @artlowel for review to see if he can review & provide additional advice.

2022-08-29 14:31 UTC, tdonohue commented on src/app/core/auth/auth.service.ts
> +  public hasToken(): boolean {
You could add a simple unit test here which is similar to how `removeToken()` is tested in `auth.service.spec.ts`.  See https://github.com/DSpace/dspace-angular/blob/main/src/app/core/auth/auth.service.spec.ts#L372-L375

2022-09-01 08:36 UTC, philipprumpf commented
Hmm. I've added some basic tests, but the 14.x tests appear to be failing in unrelated tests. Is this expected?

2022-09-01 13:29 UTC, artlowel commented
@philipprumpf yes the e2e tests sometimes fail at random. I'll restart them

2022-09-07 16:19 UTC, atarix83 requested changes
thanks @philipprumpf  for this PR.

it overall looks good, i've only found an issue that can be easily resolved.
Essentialy after restarting the rest server now the login methods are retrieved correctly but an error is shown in the login form as you can see in the screenshot

![Schermata da 2022-09-07 17-28-13](https://user-images.githubusercontent.com/2486489/188927937-f308ea4f-063f-4686-9c77-7d9558c7ac33.png)

this can be easily resolved by clearing the property `error` of the auth state when the action RETRIEVE_AUTH_METHODS is dispatched

2022-09-08 10:47 UTC, philipprumpf commented
@atarix83 Thanks! That makes sense, yes, I'll make the change.

2022-09-15 17:28 UTC, tdonohue commented
@philipprumpf : Just a friendly reminder that this PR is on your plate to do minor updates.  If you'd like this included in 7.4, we'd need those updates done ideally in the next week... any PR not merged by the end of Sept will be rescheduled for the next release (7.5 due in Feb).  So, the quicker you can make updates, the quicker we can get this re-reviewed and ready to go!

2022-09-19 08:23 UTC, philipprumpf commented
@tdonohue Thanks!

@atarix83 Thanks again for the review. I've updated the PR.

2022-09-22 09:51 UTC, atarix83 approved these changes
thanks @philipprumpf  LGTM

2022-09-22 16:56 UTC, tdonohue requested changes
@philipprumpf :  When I try to reproduce the error describe in #1793, I seem to be hitting an infinite loop...the page never reloads.

Here's what I'm trying:
1. Start up the frontend using the latest `main` code with this PR also installed.
2. Login via the UI
3. Restart the backend.  Wait for it to complete restarting
4. Click reload in my browser window (where I had previously logged into the UI).
5. At this point the browser window hangs & never reloads.  If I look at the backend logs (dspace.log), I see that it appears to be encountering an infinite loop... I see the same requests to `/server/api/authn/status` over and over and over again.  It never ends, until I shutdown the UI.

I **cannot** reproduce this infinite loop (browser window hanging) if I use the latest UI code on `main`.  So, it appears to be caused by this PR.   

**Finally,** I've also noticed that when I run the latest `main`, **I can NO LONGER REPRODUCE #1793**.  This makes me wonder if we've fixed this in a different manner (almost by accident) in a different recent PR.  That may mean this particular PR can just be closed.

2022-09-29 07:34 UTC, philipprumpf commented
I agree this particular PR addresses a problem that no longer happens (or at least happens differently - if I notice it again, I'll open a new PR against 7.4)

2022-09-29 07:34 UTC, closed without merging