Cst 7757
DSpace/dspace-angular pull request #2017
Opened 2022-12-30 08:41 UTC by atarix83

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #803 (if this fixes an issue ticket)
* Requires DSpace/DSpace#`pr-number` (if a REST API PR is required to test this)

## Description
This PR provides the opportunity to manage subscriptions by UI, in particular : 
- to subscribe/unsubscribe on the community/collection/item page itself
- to show an overview of active subscriptions with the ability to remove them

## Instructions for Reviewers
To test this PR you should run the UI against this REST PR. 
Navigate to a DSO (community, collection or items) and try to subscribe to it. You can try to change the subscription option once you have alredy subscribed to the DSO. 
Navigate to the subscriptions overview page to manage all the active subscriptions created.

List of changes in this PR:
* Added to each DSO page a button to subscribe to itself
![Schermata da 2022-12-29 18-50-11](https://user-images.githubusercontent.com/2486489/210050479-37f37d38-0224-46f5-b963-4eb97e183ae6.png)

* Created a modal to allow to subscribe daily/weekly/monthly updates
![Schermata da 2022-12-29 18-50-19](https://user-images.githubusercontent.com/2486489/210050601-9d92767d-025c-4816-9e2e-2c60298b8955.png)

* Created a new entry to the user menu to access the subscriptions overview page
![Schermata da 2022-12-29 18-50-36](https://user-images.githubusercontent.com/2486489/210050824-aaa65637-5919-466d-be0d-495fd89c5220.png)

* Created a page to see the overview of user subscriptions and manage them
![Schermata da 2022-12-29 18-50-42](https://user-images.githubusercontent.com/2486489/210050907-7b4028b1-bef5-44e1-a7c6-7ca1efaf57fd.png)

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-01-19 21:05 UTC, mwoodiupui commented
I am not seeing my Community and Collection subscriptions on the subscriptions overview page.  Item subscriptions do appear.  When I navigate to a Community or Collection to which I have subscribed, the subscriptions dialog shows the subscription as expected.  I see the rows I would expect in the `subscription` and `subscription_parameter` tables.

2023-02-01 16:52 UTC, tdonohue requested changes
@atarix83 : I tested & reviewed this today.  The basics work, but I found quite a few small bugs.

1. A user's "Subscription" page doesn't automatically refresh when new subscriptions are added.  How to reproduce:
    * Login as a user. Visit the "Subscription" page.  It should be empty initially.
    * Now, browse to a Community/Collection or Item and subscribe to it.
    * Go back to your "Subscription" page.  It will still be empty.
    * Click reload in your browser window.  Now, you'll finally see the subscription.
    * (This same issue occurs even if you have subscriptions already and add a new one. The new one won't appear until you reload your browser)
2. The Subscription popup modal lists "daily, monthly, weekly" (in that order).  Ideally, it should say "Daily, Weekly, Monthly".  The options should be capitalized, and "Weekly" should appear *before* "Monthly" as it's a shorter time period.
3. It's possible to add an **empty** frequency subscription by doing the following:
    * Create an existing subscription.
    * Go back to that same object and click "Subscription" again.  This edits the existing subscription.
    * **Unselect** all of the content options.  Click Submit.
    * The subscription is saved, but it now has no frequency.  This shouldn't be valid, as a frequency currently seems to be required.  **Instead, the subscription should be deleted.**
4. When looking at your Subscriptions (Under the user menu), they always have an empty Subject, making them impossible to tell apart.  Clicking delete also shows an empty name.  Here's a screenshot:
![empty-subscription-names](https://user-images.githubusercontent.com/483997/216108153-e404ec18-ae90-428a-bda3-82cf8ab19efa.png)
5. The Subscription modal popup should include the **name** of the object you are subscribing too.  Otherwise, it's difficult to manage subscriptions from the User menu.  Clicking "Edit" action in that list of subscriptions displays a popup that doesn't say which subscription you are editing.

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.ts
> +export class DsoPageSubscriptionButtonComponent implements OnInit {
Please add a description or TypeDocs to describe what this component does.

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.html
> +        [ngbTooltip]="'item.page.subscriptions.tooltip' | translate"
This button is failing accessibility tests because it has no `title` or `aria-label`. Please add one or both.  They can simply use the same i18n key.

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/subscriptions/models/subscription.resource-type.ts
> + * The resource type for Group
This comment is obviously wrong.  This is a for a Subscription.

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/subscriptions/subscription-modal/subscription-modal.component.ts
> +export class SubscriptionModalComponent implements OnInit {
Please add comments or TypeDocs to describe the overall purpose of this component

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/subscriptions/subscription-modal/subscription-modal.component.ts
> +  submit() {
This entire `submit()` method has a lot of messages from Codecov about missing tests/specs.  It looks like we are missing tests for what should happen when the user clicks "submit".  Right now, the specs only look to test that the form loads properly in the modal window.

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/subscriptions/subscription-view/subscription-view.component.ts
> +export class SubscriptionViewComponent {
Again please add a description or TypeDocs to describe how/where this component is used.

2023-02-01 16:52 UTC, tdonohue commented on src/app/shared/subscriptions/subscriptions-data.service.ts
> +export class SubscriptionsDataService extends IdentifiableDataService<Subscription> {
It looks like this service is missing specs.  I'm not seeing a `subscriptions-data.service.spec.ts` file.

2023-02-01 16:52 UTC, tdonohue commented on src/app/subscriptions-page/subscriptions-page.component.ts
> +export class SubscriptionsPageComponent implements OnInit, OnDestroy {
Again, please add description or typedocs to describe where this component is used

2023-02-01 16:52 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "item.page.subscriptions.tooltip": "Subscribe",
I find it odd that many of the subscription i18n tags start with "item.page" when they are obviously used for *Communities, Collections and Items*.  These same keys are used for all DSOs.

Maybe these should just be named `subscriptions.tooltip", etc (drop the entire "item.page" par, and move these down with the other `subscriptions.*` keys)?

I don't think these should start with "item.page" as that implies these are only used for items

2023-02-03 23:03 UTC, davide-negretti commented
Hi @tdonohue, I made the requested changes

> A user's "Subscription" page doesn't automatically refresh when new subscriptions are added

Fixed (the page previously used the cached values)

> The Subscription popup modal lists "daily, monthly, weekly" (in that order)

Order fixed

> It's possible to add an empty frequency subscription

I disabled the "Submit" button when no frequencies are selected. The button is also disabled if the user haven't changed the selected frequencies.

> When looking at your Subscriptions (Under the user menu), they always have an empty Subject, making them impossible to tell apart. Clicking delete also shows an empty name. 

Fixed (some parameters have been renamed on back-end)

> The Subscription modal popup should include the name of the object you are subscribing too. Otherwise, it's difficult to manage subscriptions from the User menu. Clicking "Edit" action in that list of subscriptions displays a popup that doesn't say which subscription you are editing.

The name of the object is now showed in the modal

![image](https://user-images.githubusercontent.com/87638927/216726892-3c1bab59-c259-4fd6-b9fc-18119c80b91a.png)

![image](https://user-images.githubusercontent.com/87638927/216727224-785efbbe-c13c-49d5-9284-0b0f7a86dd57.png)


Requested changes to the code (comments and specs) are still in progress

2023-02-06 22:27 UTC, tdonohue requested changes
@davide-negretti and @atarix83 : Thanks for the updates.  This is looking better, but I noticed that not all my prior feedback has been addressed. 

First, the popup, is still showing the order of checkboxes to be "Daily, Monthly, Weekly", even though it's supposed to down be "Daily, Weekly, Monthly".  Here's a screenshot:
![Add-delete](https://user-images.githubusercontent.com/483997/217100355-1d692729-272a-4b77-9dba-6cd11853d22a.png)

As also noted on that screenshot, if it's easy to do so, I'd also recommend adding a "Delete" button to that popup. Currently, if you uncheck all options, the "Submit" button disables... this makes it appear that you cannot unsubscribe (obviously though, it is possible to unsubscribe from the user's "Subscription" menu though).  This is a minor usability issue, so we could leave it as is for now, if it's too complex.

A few other inline comments/suggestions, including some notes on prior feedback that was overlooked.  Overall, though, the behavior here looks good. I think there's just minor cleanup to do now.

2023-02-06 22:27 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "subscriptions.table.empty.message": "You have not subscribed any notification yet. To subscribe notification about an object please use the contextual menu in the object detail view",
Small rewording suggestion:  "You do not have any subscriptions at this time. To subscribe to email updates for a Community or Collection, use the subscription button on the object's page."

2023-02-06 23:16 UTC, davide-negretti commented
Hi @tdonohue, as mentioned in my previous comment the changes concerning comments and test coverage are still in progress, I only pushed the changes concerning interface (except the one about frequency order that my IDE did not push). Missing changes should be ready tomorrow, I'll also check the additional requests as soon as possible

2023-02-08 17:37 UTC, atarix83 commented
@tdonohue 

Regarding this

> As also noted on that screenshot, if it's easy to do so, I'd also recommend adding a "Delete" button to that popup. Currently, if you uncheck all options, the "Submit" button disables... this makes it appear that you cannot unsubscribe (obviously though, it is possible to unsubscribe from the user's "Subscription" menu though). This is a minor usability issue, so we could leave it as is for now, if it's too complex.

I think the edit modal should be intended only for changing the preferences, indeed we've added the validation to check if at least one option is selected. To complete unsubscribe the delete button should be use instead. Now the functionalities are quite separated and could be difficult to refactor it
Maybe we can simply add an info box message in the subscription page with a small explanation. Do you agree  ?

2023-02-08 18:23 UTC, tdonohue commented
@atarix83 : It's fine to add a note in that box which says something like: 

`To remove this subscription, please visit the "Subscriptions" page under your user profile`

2023-02-08 18:58 UTC, davide-negretti commented
Hi @tdonohue, I made the remaining changes:
- missing tests
- delete instructions
- badge component
- frequency order

![image](https://user-images.githubusercontent.com/87638927/217625547-db2445f8-2f4a-4da9-9c31-2bda656ee24f.png)

2023-02-08 21:12 UTC, tdonohue reviewed
Thanks @davide-negretti and @atarix83 :  This is looking good now.  Just one *minor* usability issue.  The new "To remove this subscription..." message should ONLY be displayed when you are editing an existing subscription.  Currently, it's always displayed on the popup... for instance this is what it looks like when creating a *new* subscription:
![new-subscribe](https://user-images.githubusercontent.com/483997/217651793-d9283c8d-5b50-4cab-a2e9-e9c285174b22.png)

Obviously, this note makes no sense unless you are **editing** an existing subscription. It doesn't need to be displayed when you are creating a new subscription.

2023-02-09 11:07 UTC, davide-negretti commented
@tdonohue I fixed the issue with the delete message, and also the issue with deleted/unaccessible items

![image](https://user-images.githubusercontent.com/87638927/217793714-973b7ef3-2288-441a-96d1-abf6ff57d754.png)

2023-02-10 15:41 UTC, tdonohue commented
@atarix83  or @davide-negretti : Could one of you rebase this against main?  It now has merge conflicts... so I'm waiting to retest this until those are resolved.  Thanks!

2023-02-10 21:20 UTC, tdonohue requested changes
@davide-negretti and @atarix83 :  Overall I'm nearly a +1 on this PR.  It's looking great.  But, I think my previous request about the "To remove this subscription..." message was misunderstood.

I was asking that this message only be displayed **when there is an existing subscription that you are editing**.   So, here's a screenshot where I've clicked on the Subscription button on a Collection & I **already** have a subscription. So, in this scenario, I expect the message **should be displayed** (but it is not).

![no-message](https://user-images.githubusercontent.com/483997/218198852-be3483a1-b612-4f71-b3dd-ea67dc0b32ff.png)

So, here's when I think it should be displayed vs not displayed:

* Click on Subscribe button on a Collection/Community homepage which you are *not* currently subscribed to.  In this scenario, you are creating a *new* subscription, so the "To remove this subscription.." should **not** be displayed, as you have no subscription.
* Click on Subscribe button on a Collection/Community homepage which you are already currently subscribed to.  In this scenario, your existing subscription options will appear, and you **should** see the "To remove this subscription..." message.  (Because you will not be able to remove your subscription from this page)
* Click on the "Edit" button on your "Subscriptions" page in the Profile.  In this scenario, the "To remove this subscription.." message should likely *not* be displayed, as you are already on the "Subscriptions page.  (That said, if it has to be displayed here, I'm OK with it.  I just want the first two bullets to be fixed)

Once this message is displayed properly & this PR has it's merge conflicts resolved, then I'm +1 this feature.  Thanks for all the hard work as this is looking good!

2023-02-13 14:47 UTC, davide-negretti commented
@tdonohue I fixed the issue with the delete messsage. Your initial request was clear but I made an error in the implementation.

2023-02-13 15:50 UTC, tdonohue approved these changes
👍 Thanks @davide-negretti and @atarix83 !  I've re-tested today, and this is now working properly. All prior feedback has been addressed.

2023-02-13 15:51 UTC, merged