Advanced workflow actions - framework & workflows `scoreReview` and `selectSingleReviewer`
DSpace/dspace-angular pull request #2039
Opened 2023-01-12 02:50 UTC by MarieVerdonck

## References
Addresses:
https://github.com/DSpace/dspace-angular/issues/770
https://github.com/DSpace/DSpace/issues/2841
Corresponding REST PR: TODO

## Description
Framework for advanced workflow steps/actions, i.e. actions that can't easily be represented by just a button (with possible modal) but will rather open in a new page.

Pages for the two already configured more advanced workflows: `selectSingleReviewer` and `scoreReview` have also been added.

*ToDo*: Add additional spec testing

## Instructions for Reviewers

#### scoreReview workflow

- As admin: 
  - Create a test collection for `scoreReview` workflow test & configured in `workflow.xml` that collection's handle for the `scoreReview` workflow
  - Set on the edit collection > assign roles tab: submitters group with a member and the workflow group 'Score Reviewers' with at least 2 members (configured `requiredUsers` is 2)
- Submit item in this collection as regular user (submitter from above)
- Log in as first member of score reviewers group
  - Go to `/mydspace?configuration=workflow` => This user should be able to claim created item in workflow
  - Click on 'Rate' option
    - Should see form with required inputs for a review (text) and rating (out of maxValue, default 10)
    - Changing config in `workflow-actions.xml` `descriptionRequired` and `maxValue` should alter this form
    - Try to submit without review if `descriptionRequired=true` => will be prevented; if set to false can still be sent / saved on item but it optional
    - Do 2 star rating with description
- Repeat as second member of score reviewers group (needs 2 different score reviewers before going towards next step in workflow)
  - Verify workflow item has rating from first reviewer in metadata under fields `workflow.score` and `workflow.review`
- Verify as original submitter the workflow item is back in submission
  - Verify as admin this item has `dc.decription.provenance` indicating it was rejected because of insufficient score (`/server/api/submission/workspaceitems/{wsiId}/item`)
  - Verify it no longer contains the `workflow` metadata
  - Submit item again
- Do the rating by the 2 score reviewers again, but now rate 2 and 4 => mean 3 (in `workflow-actions.xml` config `minimumAcceptanceScore` determines minimum mean)
  - Verify as admin this item has `dc.decription.provenance` indicating it was accepted with mean score & reviews entered (`/server/api/core/items/{itemUuid}`)
  - Verify it nog longer contains the `workflow` metadata

#### selectSingleReviewer workflow

- As admin: 
  - Create a test collection for `selectSingleReviewer` workflow test & configured in `workflow.xml` that collection's handle for the `selectSingleReviewer` workflow (configure in edit collection > assign roles the submitters group with at least 1 submitter)
  - Create two repository wide groups named 'ReviewManagers' (at least 1 member) and 'Reviewers' (at least 6 members, to test pagination)
    - Make the 'ReviewManagers' a subgroup of Admin (see ToDo below)
- Submit item in this collection as regular user (submitter from above)
- Log in as a member of 'ReviewManagers'
  - Go to `/mydspace?configuration=workflow` => This user should be able to claim created item in workflow
  - Click on 'Select Reviewer' option
    - Verify the members of the 'Reviewers' group are listed as options to select from (config `action.selectrevieweraction.group = Reviewers`) - test pagination
    - Select 1 or more members as reviewers and confirm (can select & unselect)
  - Log in as (one of) selected reviewer(s)
    - Go to `/mydspace?configuration=workflow` => This user should have the item it was selected as reviewer for already claimed (auto assign selection configured) and should have buttons for options: accept, reject (with reason) and decline task
    - 4 cases:
      - Accept => Item should get archived
        - As admin: Verify info about which workflow step approved it and which user/reviewer reviewed it  in item's md `dc.description.provenance`
      - Reject with reason
        - Original submitter still exists => Workflow item back to workspace item for original submitter (email sent & provenance)
          - Verify as admin this item has `dc.decription.provenance` indicating it was rejected including who rejected it with their entered reason (`/server/api/submission/workspaceitems/{wsiId}/item`)
        - Original submitter no longer exists => Workflow item is deleted
      - Decline => Workflow is restarted so 'ReviewManager' needs to once again claim workflow item and select reviewers

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [ ] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-01-26 17:10 UTC, corrad82-4s commented
Hi @MarieVerdonck , I am testing this PR. Don't know if this is just a local problem, but when I try to Rate an item, by leaving blank the "Review" field, 
![image](https://user-images.githubusercontent.com/70699836/214902162-a066cb09-1d3e-4d68-b469-1020463922bd.png)

I am correctly asked to fill it, but when I go back to the textbox, field focus is lost after first digit is made. Not a big issue, but I wanted to report it.

2023-01-27 16:44 UTC, corrad82-4s reviewed
I have been testing this PR, following the steps suggested in PR description, apart "Decline" scenario, see above, all has been working as expected. 
Listing here some notes, in addition to what I have already reported in a previous comment.

Regarding `selectSingleReviewer`: 
* I had some problems with pagination of reviewers group list: when I go to pages higher than first and then click "confirm" or "cancel" buttons, despite one or many reviewers have been selected, I am not brought back to myDspace page. 
* Maybe it is a problem of my local instance, but selected reviewers cannot perform "return to pool"
* I was unable to test "Decline" scenario, not sure if it is a problem of my local instance, but I got a "500" http error code back from REST API, The point involved in backend is https://github.com/DSpace/DSpace/pull/8629#discussion_r1089120737 and this is the exception found  
``` 
2023-01-27 13:27:18,776 ERROR 61fbfc6c-85a2-481f-86a6-7161eb9c0915 96a4fa59-1ea5-4e69-a0da-9bb892c5598f org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ Batch entry 0 update public.cwf_workflowitem set collection_id='572dc20b-0b50-4e83-8949-9b77c0684029'::uuid, item_id='c58197b5-21a4-4671-9bfe-fb7469838a2f'::uuid, multiple_files='FALSE', multiple_titles='FALSE', published_before='FALSE' where workflowitem_id=315 was aborted: ERROR: duplicate key value violates unique constraint "cwf_workflowitem_item_id_key"
  Detail: Key (item_id)=(c58197b5-21a4-4671-9bfe-fb7469838a2f) already exists.  Call getNextException to see other errors in the batch.
2023-01-27 13:27:18,776 ERROR 61fbfc6c-85a2-481f-86a6-7161eb9c0915 96a4fa59-1ea5-4e69-a0da-9bb892c5598f org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ERROR: duplicate key value violates unique constraint "cwf_workflowitem_item_id_key"
  Detail: Key (item_id)=(c58197b5-21a4-4671-9bfe-fb7469838a2f) already exists.
2023-01-27 13:27:18,777 ERROR 61fbfc6c-85a2-481f-86a6-7161eb9c0915 96a4fa59-1ea5-4e69-a0da-9bb892c5598f org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
	at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
	at org.dspace.core.AbstractHibernateDAO.executeCriteriaQuery(AbstractHibernateDAO.java:427) ~[classes/:?]
	at org.dspace.core.AbstractHibernateDAO.list(AbstractHibernateDAO.java:162) ~[classes/:?]
	at org.dspace.authorize.dao.impl.ResourcePolicyDAOImpl.findByDso(ResourcePolicyDAOImpl.java:51) ~[classes/:?]
	at org.dspace.authorize.ResourcePolicyServiceImpl.find(ResourcePolicyServiceImpl.java:87) ~[classes/:?]
	at org.dspace.authorize.AuthorizeServiceImpl.getPolicies(AuthorizeServiceImpl.java:488) ~[classes/:?]
	at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.grantSubmitterReadPolicies(XmlWorkflowServiceImpl.java:277) ~[classes/:?]
	at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.start(XmlWorkflowServiceImpl.java:214) ~[classes/:?]
	at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.start(XmlWorkflowServiceImpl.java:88) ~[classes/:?]
	at org.dspace.xmlworkflow.state.actions.processingaction.SingleUserReviewAction.processDecline(SingleUserReviewAction.java:114) ~[classes/:?]
```

2023-01-27 21:10 UTC, tdonohue requested changes
@MarieVerdonck :  Gave this a review and test today.  Overall, it works well! But, I noticed some bugs as well.

**For ScoreReview**
* I noticed the same bug that @corrad82-4s mentions here: https://github.com/DSpace/dspace-angular/pull/2039#issuecomment-1405328076   It's impossible to fill out the "Review" field once it is in an error state.
* I also noticed that when you attempt to submit the rating form **without** filling out the "Rating" field, you see this generic error:
![error-with-no-rating](https://user-images.githubusercontent.com/483997/215198090-88a03cac-d9a0-42ed-8538-cf9b1926332e.png)
I expected a more specific error that says "Please fill out a rating".. or just highlight the "Rating" field in red.

Beyond those small errors, ScoreReview works well!  I verified it auto-rejects when the score is too low (as configured) and accepts if the score is high enough.  Also verified "workflow" fields disappear and turn into "dc.description.provenance" as the item changes state.

**For SingleReviewer**
* Again, I noticed the same issues as @corrad82-4s noted: https://github.com/DSpace/dspace-angular/pull/2039#pullrequestreview-1273049955  I hit all 3 of these same issues on my end.
    * If you page to the next page of EPersons after selecting a reviewer, clicking "Submit" keeps you on the select reviewer form. You never exit the form
    * Once a reviewer is selected & you login as that reviewer, the "Return to Pool" button doesn't work
    * "Decline" button also doesn't work for the selected reviewer.  (Accept & Reject work fine though)
* I believe the "Return to Pool" button should not even be displayed once a reviewer is assigned.  It looks like it's out of place because it does the same thing as "Decline".  See this screenshot:  
![return-to-pool-button](https://user-images.githubusercontent.com/483997/215199403-ef0e3e2b-ee3d-4af5-9771-cd58c095b67a.png)

Overall, SingleReviewer also works well... just small issues as noted above, and we need to ensure all buttons are correct & working.

I have a few small inline code comments below too... mostly just requests for more code comments / Typesdocs.

2023-02-07 22:04 UTC, MarieVerdonck commented
@tdonohue, @corrad82-4s, I think @alexandrevryghem addressed all mentioned issue, and gave it a test as well again with the latest REST. Notably we couldn't recreate your issue with 'Decline' option in 2nd step of `SelectReviewers` (see notes below), if you still encounter this issue, could you perhaps check if anything meaningful is logged / get error & stack trace from `DSpaceApiExceptionControllerAdvice`

**SelectReviewers**

- Select reviewers page not returning to /myDspace if not on first page resolved
- Return to pool option removed for single review action options (No longer present on any workflow step, must be defined as one of the options in REST)
- Issue with Decline couldn't be reproduced, but now the declined wfi in /myDspace page is replaced with coloured box with message "Declined, sent back to Workflow Manager's workflow" like is done for Accept/Reject (reject message changed to "Rejected, sent back to submitter", since it said declined, which is not the same in this step/action)
  - To be clear if 1 reviewer declines the task it is sent back to the workflow manager to claim and select new reviewers. There was no time left in implementation to make it so it only is sent back if **all** selected reviewers press decline

**ScoreReview**

- Should now be able to fill in Review field if in error state
- No longer possible to submit with filling out Rating (does mean min rating is 1 star, not 0, but now can't be forgotten)

2023-02-08 17:56 UTC, tdonohue requested changes
@MarieVerdonck :  I re-reviewed & re-tested this today.  First off, **almost all the bugs** are fixed.  The only one that I can still reproduce is that Decline button issue with SelectReviewers.  I've tried it twice, and that button doesn't work for me.

Here's how I've reproduced it (while running the UI in prod mode: `yarn build:prod; yarn serve:ssr`):
1. Setup a collection with SelectReviewers
2. Login as a user with only submit privileges to that Collection. Submit a new item
3. Logout & Login as a user in "ReviewManagers" group & assign the review to another user. (In my case I assigned it to someone who is a non-Admin, but I don't think this matters)
4. Logout & Login as the assigned user.  Find the assigned task in your MyDSpace and click "Decline".  A 500 exception occurs.  In the dspace.log I see this long ConstraintViolation error (I've included some INFO statements just before the error in case they are useful to provide context)

```
2023-02-08 17:41:35,237 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.xmlworkflow.XmlWorkflowServiceImpl @ test@gmail.com::return_to_workspace:workflow_item_id=79workspace_item_id=7566
2023-02-08 17:41:35,253 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.xmlworkflow.XmlWorkflowServiceImpl @ test@gmail.com::abort_workflow:workflow_item_id=79item_id=93cd2544-f8df-458e-9580-8444d9418feccollection_id=908adbda-2d13-4d15-831d-5e02ac747ec3eperson_id=222a7714-f945-46e1-85f1-4157a6d19d0c
2023-02-08 17:41:35,254 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.xmlworkflow.storedcomponents.XmlWorkflowItemServiceImpl @ test@gmail.com::update_workflow_item:workflowitem_id=81
2023-02-08 17:41:35,254 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.content.Item @ test@gmail.com::update_item:item_id=93cd2544-f8df-458e-9580-8444d9418fec
2023-02-08 17:41:35,254 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.content.Item @ test@gmail.com::update_item:item_id=93cd2544-f8df-458e-9580-8444d9418fec
2023-02-08 17:41:35,256 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.content.Item @ test@gmail.com::update_item:item_id=93cd2544-f8df-458e-9580-8444d9418fec
2023-02-08 17:41:35,258 INFO  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl @ HHH000010: On release of batch it still contained JDBC statements
2023-02-08 17:41:35,258 ERROR 1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.hibernate.engine.jdbc.batch.internal.BatchingBatch @ HHH000315: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 update public.cwf_workflowitem set collection_id='908adbda-2d13-4d15-831d-5e02ac747ec3'::uuid, item_id='93cd2544-f8df-458e-9580-8444d9418fec'::uuid, multiple_files='FALSE', multiple_titles='FALSE', published_before='FALSE' where workflowitem_id=81 was aborted: ERROR: duplicate key value violates unique constraint "cwf_workflowitem_item_id_key"
  Detail: Key (item_id)=(93cd2544-f8df-458e-9580-8444d9418fec) already exists.  Call getNextException to see other errors in the batch.], SQL: update public.cwf_workflowitem set collection_id=?, item_id=?, multiple_files=?, multiple_titles=?, published_before=? where workflowitem_id=?
2023-02-08 17:41:35,258 WARN  1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ SQL Error: 0, SQLState: 23505
2023-02-08 17:41:35,258 ERROR 1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ Batch entry 0 update public.cwf_workflowitem set collection_id='908adbda-2d13-4d15-831d-5e02ac747ec3'::uuid, item_id='93cd2544-f8df-458e-9580-8444d9418fec'::uuid, multiple_files='FALSE', multiple_titles='FALSE', published_before='FALSE' where workflowitem_id=81 was aborted: ERROR: duplicate key value violates unique constraint "cwf_workflowitem_item_id_key"
  Detail: Key (item_id)=(93cd2544-f8df-458e-9580-8444d9418fec) already exists.  Call getNextException to see other errors in the batch.
2023-02-08 17:41:35,258 ERROR 1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ERROR: duplicate key value violates unique constraint "cwf_workflowitem_item_id_key"
  Detail: Key (item_id)=(93cd2544-f8df-458e-9580-8444d9418fec) already exists.
2023-02-08 17:41:35,259 ERROR 1af8e0bf-3051-4b70-b2b1-f7c5d680753f 04d014cf-e7c8-4891-9da1-9308f25b41e2 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
        at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76) ~[hibernate-core-5.6.5.Final.jar:5.6.5.Final]
        at org.dspace.core.AbstractHibernateDAO.executeCriteriaQuery(AbstractHibernateDAO.java:427) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.core.AbstractHibernateDAO.list(AbstractHibernateDAO.java:162) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.authorize.dao.impl.ResourcePolicyDAOImpl.findByDso(ResourcePolicyDAOImpl.java:51) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.authorize.ResourcePolicyServiceImpl.find(ResourcePolicyServiceImpl.java:87) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.authorize.AuthorizeServiceImpl.getPolicies(AuthorizeServiceImpl.java:488) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.grantSubmitterReadPolicies(XmlWorkflowServiceImpl.java:277) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.start(XmlWorkflowServiceImpl.java:214) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.start(XmlWorkflowServiceImpl.java:88) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.xmlworkflow.state.actions.processingaction.SingleUserReviewAction.processDecline(SingleUserReviewAction.java:127) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.xmlworkflow.state.actions.processingaction.SingleUserReviewAction.execute(SingleUserReviewAction.java:65) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.doState(XmlWorkflowServiceImpl.java:381) ~[dspace-api-7.5-SNAPSHOT.jar:7.5-SNAPSHOT]
        at org.dspace.app.rest.repository.ClaimedTaskRestRepository.action(ClaimedTaskRestRepository.java:214) ~[classes/:7.5-SNAPSHOT]
        at org.dspace.app.rest.repository.ClaimedTaskRestRepository.action(ClaimedTaskRestRepository.java:67) ~[classes/:7.5-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository.action(DSpaceRestRepository.java:480) ~[classes/:7.5-SNAPSHOT]
        at org.dspace.app.rest.repository.DSpaceRestRepository$$FastClassBySpringCGLIB$$615525f9.invoke(<generated>) ~[classes/:7.5-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.20.jar:5.3.20]
        at org.springframewor [...]

2023-02-09 14:46 UTC, atarix83 requested changes
thanks @MarieVerdonck 

I've not yet fully reviewed but I'm adding a first suggestion

2023-02-09 16:12 UTC, artlowel commented on package.json
> +    "ngx-bootstrap": "7.1.2",
As discussed in today's meeting: I agree, we shouldn't introduce a second library for bootstrap. However, ngx-bootstrap is properly treeshakable, so this only adds the js code needed for the rating right now. So we'll keep that as is in order to get this PR merged in time for 7.5, and then create a separate ticket to replace the rating component with ng-bootstrap's later

2023-02-09 22:44 UTC, tdonohue approved these changes
👍 Thanks @MarieVerdonck and @alexandrevryghem !  I've retested this today.  I've verified that the fixes to the backend PR have fixed the bug related to the "Decline" button (in SingleReviewer workflow).  I've also verified that after the removal of `ngx-bootstrap`, the scoreReview workflow is still working properly.

@atarix83 : Please give this a re-review, as @alexandrevryghem was able to remove `ngx-bootstrap` as you requested.

2023-02-09 22:45 UTC, tdonohue commented on package.json
> +    "ngx-bootstrap": "7.1.2",
Turns out that @alexandrevryghem was able to remove `ngx-bootstrap` in this PR.  Thanks @alexandrevryghem !

2023-02-10 11:05 UTC, atarix83 reviewed
@MarieVerdonck 

I've tested it and it's overall good. 
I just have to report a small malfunctions when navigating among the new workflow pages and the mydspace page.

- with the rating workflow when I search for a workflow item which title contains a space e.g. 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2486489/218073981-17f04af2-3f60-470d-b864-33c9264ee307.png)

and then from the workflow rating page i click on the back button, I'm redirected to the previous page but the url contains wrong encoded chars and as a result the item is not found because the search is wrong 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/2486489/218075534-1353e3af-f2da-4ca3-b110-9e1be4cb1526.png)

- with the selecting reviewer(s) workflow instead when passing back from the select reviewer(s) page and the mydspace page the query search is not maintened

This is not a big issue but if it can be resolved quickly it'd be great.

For the rest this is a +1 for me

2023-02-10 16:24 UTC, tdonohue commented
@MarieVerdonck & @alexandrevryghem  : My apologies, another merger caused more merge conflicts here.  

@atarix83 : Can you re-review this today?  If not, I can try and verify the issues you found are now fixed

2023-02-10 17:43 UTC, atarix83 approved these changes
thanks @MarieVerdonck 

it's working properly now, after the merge conflicts are resolved this PR can be merged

2023-02-10 19:40 UTC, merged