disabled the posibility to change the collection for workflow items to prevent errors
DSpace/dspace-angular pull request #2143
Opened 2023-03-10 03:48 UTC by CrisGuzmanS

Hello @tdonohue i have already disabled the posibility to change the collection for workflow items to prevent errors. 🥳 

## References
* Fixes #2140
* Fixes https://github.com/DSpace/DSpace/issues/7965

## Description
This is my approach to prevent that the user can change the collection for a workflowitem to prevent errors, because the modification for the workflowitem collection is not trivial.

## Instructions for Reviewers
1. Login as administrator
2. go to Workflowitems list
3. Edit any workflowitem
4. Try to change the collection (you should no be able to do it)
5. Create any item
6. Try to change the collection (you should be able to do it)

List of changes in this PR:
* I injected collectionModifiable in workflow-edit-page-routing.module.ts
* if collectionModifiable is not injected, that means that the collection will be modifiable.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-03-10 18:37 UTC, tdonohue commented
@CrisGuzmanS : Thanks for the quick work here!  I just wanted to let you know, it appears these changes break some of our automated tests (`yarn test`).  I suspect the tests themselves need to be fixed / updated though... so, if you could look into fixing them in this PR that'd be the best scenario.

2023-03-11 01:57 UTC, CrisGuzmanS commented
Thank you @tdonohue for your feedback, and sorry for those errors, i am struggling with my chrome binary from local, this is why i do not check the testing section in my pull request, so i am waiting for github to check if my test is passing. But i am going to work on this task, thank you Tim

2023-03-12 21:38 UTC, CrisGuzmanS commented
Hello @tdonohue ✋ i already fixed the test issues 👍 .

2023-03-27 21:48 UTC, tdonohue requested changes
@CrisGuzmanS : This looks good overall and it works.  However, the variable "collectionModifiable" is not working as it is described.   I'd expect that setting "collectionModifiable=true" should mean that you can modify the collection (i.e. dropdown is enabled), while "collectionModifiable=false" should mean that you **cannot** modify the collection (i.e. dropdown is disabled).  Currently, you've implemented the opposite (see inline comment below), which I think looks confusing.

If you could simply switch the behavior of this setting, I think that'd make more sense.  Other than that, this code all works and looks good.

2023-03-27 21:48 UTC, tdonohue commented on src/app/submission/form/collection/submission-form-collection.component.html
> +            [disabled]="(processingChange$ | async) || collectionModifiable"
"collectionModifiable=true" should mean that the collection *can* be modified (i.e. dropdown should be enabled).  But, here it's the opposite... "collectionModifiable=true" means that this dropdown is **disabled**.

I'd recommend we change this to be `|| !collectionModifiable` and then change `workflowitems-edit-page-routing.module.ts` to set it to `false`.

2023-03-30 18:23 UTC, CrisGuzmanS commented
Hello @tdonohue i have already attended your feedback. Please, let me know if everything is ok

2023-03-30 21:49 UTC, tdonohue approved these changes
👍 Thanks @CrisGuzmanS !  This looks good now. Tested it and it works well too.

2023-03-30 21:50 UTC, merged