Update to fixe french labels for System-wide alert
DSpace/dspace-angular pull request #2154
Opened 2023-03-17 19:07 UTC by pilasou

Add translations for the System wide alert feature as well other various missing parameters.

2023-03-23 19:53 UTC, tdonohue requested changes
@pilasou : Thanks for the PR!  Currently though this is failing to build.  It looks like the JSON5 file is accidentally invaild.  I'm seeing this error when I try to build:
```
Error: JSON5: invalid character '\"' at 6186:3
```

I think I found the issue, see my comment below.  Once it's fixed, I can re-test.

2023-03-23 19:53 UTC, tdonohue commented on src/assets/i18n/fr.json5
>    "idle-modal.extend-session": "Prolonger la session"
I think the issue is on this line... there should be a comma at the end of this line

2023-03-28 21:51 UTC, merged

2023-03-29 13:27 UTC, mhvezina commented on src/assets/i18n/fr.json5
> +  "item.edit.identifiers.doi.status.IS_RESERVED": "Réseré",
Should be "Réservé" instead of "Réseré".

2023-03-29 13:27 UTC, mhvezina commented on src/assets/i18n/fr.json5
> +  "item.edit.register-doi.description": "Réviser les identifiants en attente and les métadonnées ci-dessous item metadata below puis cliquer sur Confirmer afin de lancer l'inscription du DOI ou sur A
Should be : "Réviser les identifiants en attente and les métadonnées ci-dessous puis cliquer sur Confirmer afin de lancer l'inscription du DOI ou sur Annuler pour interrompre l'inscription"

2023-03-29 13:27 UTC, mhvezina commented on src/assets/i18n/fr.json5
> +  "supervisedWorkspace.search.results.head": "Items supervisés",
Suggestion : "Documents supervisés" or "Éléments supervisés".