Implemented i18n cache busting
DSpace/dspace-angular pull request #2464
Opened 2023-08-27 14:28 UTC by alexandrevryghem

## References
* Fixes #2461

## Description
In this PR I added hashes to the translation files & ensured that the translation files are retrieved with those hashes.

## Instructions for Reviewers
List of changes in this PR:
- Created a function to calculate the hashes of the json5 files and stored them using the `EnvironmentPlugin` to be able to retrieve them in the app using `process.env.languageHashes`
- Customised the `CopyWebpackPlugin` to add the hash to the json file name
- Customised the `TranslateBrowserLoader` & `TranslateServerLoader` to retrieve the language file with the hash saved in `process.env.languageHashes`

**Guidance for how to test & review this PR:**
Test the following in both dev & prod mode:
- Start your angular and check that all the translation keys are correctly displayed in both the default language (by default `en.json5`) & other random language (the reason you also need to test this in another random language is because in prod mode the default language is already included in the `TransferState` so both mechanisms need to be tested)
- Make a change to a certain key in both the default language json5 file) and one other random language file
- By refreshing the page you should still be able to see the changes directly in dev mode. In prod mode you should now be able to see the changes directly in both languages without hard refreshing the page.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2023-10-12 08:50 UTC, artlowel requested changes
Thanks @alexandrevryghem!

The hashing thing works great, however I'd leave out the syncing of the i18n files during production builds. I'd rather see https://github.com/DSpace/dspace-angular/issues/2340 fixed using a github workflow task for example, where every time a PR is merged that changes an i18n message, a new PR is generated that syncs all i18n files

I don't like the fact that with this PR, the i18n files used in production don't contain the exact same messages as the ones in the src folder.

2023-10-12 15:04 UTC, tdonohue commented
@alexandrevryghem : I wanted to briefly note that I agree with @artlowel 's [feedback above](https://github.com/DSpace/dspace-angular/pull/2464#pullrequestreview-1673639144).  I'd recommend we remove any automatic syncing of i18n files from this PR and solve it later in a separate PR. This PR could then just concentrate on the new hashed files for i18n.

2023-10-13 09:08 UTC, alexandrevryghem commented
@tdonohue I removed the commit, and updated the PR description, but I can't unlink issue #2340, can you please fix this 🙏

2023-10-13 14:43 UTC, tdonohue commented
@alexandrevryghem : I cannot seem to remove the link to the other ticket (#2340) either 😞   It appears to be a GitHub bug.  We'll just need to reopen that ticket if it ends up closing automatically when this PR is merged.  (Or maybe GitHub will eventually correct itself)

2023-10-26 07:06 UTC, Leano1998 commented
Hej, 
thank you @alexandrevryghem for the PR. I tested it as well and it worked perfectly for me!

2023-10-26 11:52 UTC, artlowel approved these changes
Thanks @alexandrevryghem!

2023-10-26 16:22 UTC, tdonohue approved these changes
👍 Thanks @alexandrevryghem !  This looks great, and I've verified this also works well when running the UI in production mode on Windows.

2023-10-26 16:22 UTC, merged