remove obsolete label element in metadata-schema.component.html
DSpace/dspace-angular pull request #2505
Opened 2023-09-19 15:10 UTC by saschaszott

This PR implements a minor HTML change which improves the "find in page" of your prefered web browser. Currently, it is not possible to search for metadata field names of the form `schema.element.qualifier` using the "find in page" function, e.g. in /admin/registries/metadata/dc.

2023-09-19 18:28 UTC, alanorth commented
Thanks @saschaszott. If I understand correctly, by "find in page" you mean the Ctrl-F / Cmd-F in the browser? I tried searching for `dc.contr` using Ctrl-F in Firefox on DSpace 7.6 and it works.

<p align="center">
  <img src="https://github.com/DSpace/dspace-angular/assets/191754/b7bc3583-805e-407c-9b56-3a6796d9a582" width="600px">
</p>

Did I understand correctly?

2023-09-20 08:00 UTC, saschaszott commented
@alanorth , the problem only arises if you search with a field name that contains **two** periods.

This screenshot was taken from Google Chrome where a search with term `dc.contributor.advisor` does not match the page content.

![image](https://github.com/DSpace/dspace-angular/assets/952735/0c287f58-4b14-4c06-a91d-873857834ed6)

2023-09-20 17:45 UTC, alanorth commented
OK, I don't use Chrome so I don't know. I can _find_ a metadata field with two dots in Firefox.

<p align="center">
  <img src="https://github.com/DSpace/dspace-angular/assets/191754/85d8adb9-e1c3-448b-a670-44bc4651ec40" width=600">
</p>

Is this because it's wrapping for some reason in Chrome, or perhaps just on your device?

2023-09-21 08:11 UTC, saschaszott commented
@alanorth , I cannot reproduce this odd behaviour in Safari. This seems to be a **Chrome** specific problem. Nevertheless, it should be fixed as Chrome has > 50% market coverage.

2023-09-21 17:36 UTC, alanorth requested changes
This introduces trailing whitespace.

2023-09-21 17:41 UTC, alanorth commented
@saschaszott I finally looked at this. The existing code doesn't make sense—why put a label with only part of the metadata field? Could have been a bug in the original code.

Anyways, I tested this and it doesn't break my find in Firefox so I'm +1. Would you feel comfortable rebasing this commit to remove the trailing whitespace? Thanks.

2023-09-22 08:41 UTC, saschaszott commented
> This introduces trailing whitespace.

Thank you for noticing - it was fixed.

2023-09-22 17:56 UTC, alanorth approved these changes

2023-09-22 17:57 UTC, alanorth commented
Thanks @saschaszott. I will squash the two commits into one before merging so the whitespace doesn't stay in git history.

2023-09-22 17:57 UTC, merged