Fix accessibility issues (part 2)
DSpace/dspace-angular pull request #2717
Opened 2023-12-17 14:18 UTC by alexandrevryghem

## References
* Fixes #2697
* Related #2683

## Description
This is a follow up PR on #2683, last time I only used Axe DevTools & Ligthouse. This time I used Wave to find additional errors. I didn't fix the header errors and warnings and also didn't fix the contrast issues because seperate PRs lready exists for those.

## Instructions for Reviewers
Instead of making a big list of changes here I seperated the fixes by page/type of issue and used the commit message to describe the fixes to facilitate the review process.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-01-29 22:55 UTC, tdonohue requested changes
@alexandrevryghem : Overall, this looks **great**!  I've verified each commit individually & verified the fixes listed in the description,..and I've only noticed a few minor issues:

1. The feedback form no longer works.  See inline comment below
2. The fix for #1176 seems to be *partial*?  I see the "Results Per Page" in the menu now has an `aria-selected=true` next to the checked value.  However, the "Sort Options" section of that same menu does NOT have that next to the checked value.  So, I think we just need to update the "Sort Options" in the same way.

Everything else looks great.  So once these minor issues can be fixed, I think this can be merged & backported to 7.6.x.

2024-01-29 22:55 UTC, tdonohue commented on src/app/info/feedback/feedback-form/feedback-form.component.html
> +      <form class="col p-0">
I cannot get the feedback form the work anymore?  It appears this `<form>` is nested under another `<form>` on line 3.  Maybe that's messing things up?

If I visit the feedback form, it loads.  But the "Send Feedback" button will not enable, even if you enter in an email and comments.

2024-01-30 22:28 UTC, alexandrevryghem commented
@tdonohue: Thnx for the feedback! I fixed both issues and amended the fixes for a cleaner history (I only updated the `FeedbackComponent` & the `PaginationComponent`)

2024-01-31 15:34 UTC, tdonohue approved these changes
👍 Thank you @alexandrevryghem !  This looks good now and everything is working as expected.  Merging & auto-porting back to 7.6.x

2024-01-31 15:34 UTC, merged