Clear url parameters for entity search tabs
DSpace/dspace-angular pull request #2734
Opened 2024-01-10 10:24 UTC by Atmire-Kristof

## References
* Fixes #2729

## Description
Clears all url parameters when switching search tabs on entity pages to avoid using non-existent filters/sort/configurations/pages etc. on the new search tab

## Instructions for Reviewers
How to test:
* Visit an entity item page containing more than one search tab, with one search tab containing a filter or sort option not available on the other tab
* Select a value for that filter/sort option
* Click the other tab
* All parameters except the tab identifier should be cleared and search is still functional
* Perform the same test, but one tab containing more pages of results than the other, selecting the last page and clicking the other tab, you should end up on the first page of the new search tab

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-01-17 16:54 UTC, Atmire-Kristof commented
Applied an additional fix for #2739, since it's related to the same issue of clearing url parameters.

2024-05-03 21:15 UTC, tdonohue commented
@Atmire-Kristof : This has code conflicts. If you wish to have it still considered for 8.0, please get this PR cleaned up and updated to latest `main`. Otherwise, we'll have to reschedule for 9.0. Thanks!

2024-05-14 16:22 UTC, tdonohue requested changes
@Atmire-Kristof : I tested/reviewed this today.  While, I can verify it fixes both #2729 and #2739, this PR is currently failing several existing specs/tests in `StartsWithDateComponent`.  Please update this PR to either pass those tests or fix those tests.

2024-05-17 06:56 UTC, toniprieto commented
I don't think #2739 should be considered a bug. The second parameter 'startWith' is used to filter the list of items by title that have the previously selected value. For example, if you select the subject 'financial therapy' on the current demo site (https://demo.dspace.org/browse/subject?value=financial%20therapy&bbm.return=5), you can then filter this list by titles that start with 'Book' (https://demo.dspace.org/browse/subject?value=financial%20therapy&bbm.return=5&bbm.page=1&startsWith=Book).

2025-06-19 13:16 UTC, nona-luypaert commented
Hi @tim and @toniprieto,

I've made a small update that does the following:

explicitly reset the page param to 1 when tab switching between related entities.
preserve the scope and query params. They're the only things that can remain constant between tabs, so it makes sense to keep them.
fix tests.
The https://github.com/DSpace/dspace-angular/pull/2735 has also been updated with this.

Finally, I merged the most recent main/dspace-7_x into the PR branches.

Regarding @toniprieto's comment above, I understand what you mean. However, the current behavior can confuse users quite easily. As that search bar is used to search browse entries first (on e.g. /browse/subject). I would expect it to continue looking for browse entries, instead of switching to items suddenly. Which I believe was also the intent of the bug report.

2025-09-05 21:46 UTC, tdonohue approved these changes
👍 Thanks @Atmire-Kristof and @nona-luypaert !  Apologies for taking so long to re-test this.  But, I can verify it's working and fixes both bugs.  The code looks good too.

2025-09-05 21:46 UTC, merged

2025-09-05 22:03 UTC, tdonohue commented
@Atmire-Kristof or @nona-luypaert : Could one of you please port this to `dspace-8_x'?  It's already ported to `dspace-7_x` via #2735 and I was able to easily cherry-pick it to `dspace-9_x` in #4674.  But, the port to `dspace-8_x` is a bit more complex it seems.