Fix for #1602 Insufficient collection information when submitting an article
DSpace/dspace-angular pull request #3327
Opened 2024-09-12 06:26 UTC by im-shubham-vish

### Description
Insufficient collection information when submitting an article.
### Instructions for Reviewers
Sometimes, the collections returned by the collection browser are indistinguishable because their names are identical to other collections and their parent communities.
For example, suppose you have two communities named "Institution A" and "Institution B," each with a subcommunity named "Reports." Both subcommunities have a collection called "Research Reports." If I want to submit an item to "Institution B > Reports > Research Reports," it's impossible to differentiate between the "Reports" subcommunity in "Institution A" and "Institution B" when searching for the "Research Reports" collection.
**Expected Behavior**
Instead of displaying only the name of the parent community, the interface should display the full hierarchy, similar to how it's done in XMLUI.
### List of Changes in this PR:
•	Added a method getHierarchicalName in sidebar-search-list-element.component.ts that returns the hierarchical name. Now, parentTitle calls getHierarchicalName instead of getParentTitle.
•	Added a method createInstanceFromDSpaceObject responsible for creating an instance of DSpaceObject.
•	Removed the maxlines argument from sidebar-search-list-element.component.html.
•	Added some CSS to the content class in truncatable-part.component.scss.
### Steps to Test and Reproduce the Behavior:
1.	Create two top-level communities named "A" and "B."
2.	Create a subcommunity named "Reports" under each top-level community.
3.	Create a collection named "Research Reports" within each "Reports" subcommunity.
4.	Try to submit an item to "B > Reports > Research Reports" and ensure that the full hierarchical name is displayed.

2024-09-12 15:53 UTC, tdonohue commented
@im-shubham-vish : Thanks for the PR.  Just a note that this is failing `lint` formatting checks.  You can see those locally by running `npm run lint`.  They are also visible in this PR if you look at the "Files changed" tab.   Some of these may be fixed automatically if you run `npm run lint-fix`

We require all PRs to pass lint formatting checks.

2024-09-27 11:58 UTC, Leano1998 commented
Hi @im-shubham-vish , 
thanks for you PR! I tested it locally and it worked perfectly. I just noticed, you kept the `parentTitle$` variable in the TypeScript file. Is there a reason for it? Because as far as I can see, you don't need it any more or do I miss something?
Also, you might adjust the spec test in the *sidebar-search-list-element.component.spec.ts* in order to test the `hierarchicalTitle$` instead of the `parentTitle$`.

2024-12-10 08:33 UTC, im-shubham-vish commented
Hi @Leano1998, 
Sorry for the late reply & thanks for your feedback! You're right we have no use case left for parentTitle$. So I've adjusted all over the possible places to use hierarchicalTitle$ instead of the parentTitle$ including spec test files. 

Please recheck once and let me know in case you've any feedback.

2025-01-22 16:49 UTC, tdonohue requested changes
@im-shubham-vish : Thanks for this PR.  I gave it a test today, and the basic functionality is working for me.  I've verified, I see the entire hierarchy in the popup for "New -> Community", "New -> Collection" and "New -> Item".   Here's what it looks like to me

![hierarchy-communities](https://github.com/user-attachments/assets/e95dbc7d-a34f-40ff-ad6a-b99ee7832620)

The only issues that I have with this PR is the way in which you've duplicated the same test over and over in several of the spec files.  I think it'd be much cleaner & smaller if you moved these tests to a single location...and Codecov (our test verification tool) would also likely stop complaining that it cannot find your tests.

If you can get your tests updated, I think this would be ready to merge.

2025-03-31 11:35 UTC, im-shubham-vish commented
@tdonohue Thanks for the feedback! I have implemented your suggestions and pushed the changes. 

Please review and let me know if you have any further feedback.

2025-04-24 22:09 UTC, tdonohue requested changes
@im-shubham-vish : Thanks for the updates.  I got back to this PR today.  It still *works* when I test it manually.  However, the tests don't appear to be running **at all**.  I don't see the output of the tests when I run `npm test`, or in the GitHub logs.  Are you getting these tests to run?

Overall, this code works.  But, I still don't see the tests working properly. It's important to have new & working tests so that this code doesn't break in the future.  See my inline comments below.

2025-04-24 22:09 UTC, tdonohue commented on src/app/entity-groups/journal-entities/item-list-elements/sidebar-search-list-elements/journal/journal-sidebar-search-list-element.component.spec.ts
> +if (expectedHierarchicalTitle) {
This `if` clause in **all tests** appears to be **skipping the test**.  When I run these tests locally (or look at the logs of the tests in GitHub), I cannot find any proof of the "JournalSidebarSearchListElementComponent" test being run below.

Are you sure these tests are running?  Could we remove this `if` statement to prove they work?

2025-04-24 22:09 UTC, tdonohue commented on src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.ts
> +  getHierarchicalName(): Observable<string> {
My prior feedback has not been addressed on this `getHierarchicalName()` method.  We need to add **new** tests to `sidebar-search-list-element.component.spec.ts` which prove that this method is properly building the hierarchical name at all times.  Otherwise, there is a risk that it will accidentally break in the future & we won't realize it.

2025-04-24 22:09 UTC, tdonohue commented on src/app/entity-groups/journal-entities/item-list-elements/sidebar-search-list-elements/journal/journal-sidebar-search-list-element.component.spec.ts
> +      createSidebarSearchListElementTests(JournalSidebarSearchListElementComponent, object, parent, hierarchicalTitle, 'title', '1234, 5678');
Since all of these tests call `createSidebarSearchListElementTests`, couldn't we move the call to `getExpectedHierarchicalTitle()` into that existing `createSidebarSearchListElementTests` method?  I don't see why we need to have the `if` or the `subscribe` above?  Is there something I'm missing here?

2025-06-19 13:27 UTC, im-shubham-vish commented
@tdonohue We have incorporated the suggestions. Kindly review and if you have any feedbacks let us know.

2025-06-21 08:32 UTC, PitbaranK commented
@tdonohue,
Kindly help us by reviewing and merging the changes in this pull request.
If you have any feedback or suggestions, please feel free to share — we’re happy to connect and make any necessary adjustments.

2025-08-18 08:00 UTC, PitbaranK commented
@tdonohue,
Could you please help us understand if we are missing anything, as this PR is still not proceeding further even after incorporating the requested changes?

@EikLoe,
Could you kindly take another look and get back on the same? Reference : https://github.com/DSpace/dspace-angular/issues/3327#issuecomment-2379107604

2025-11-04 07:49 UTC, PitbaranK commented
@tdonohue,
Thanks for the review. We have incorporated all the changes requested https://github.com/DSpace/dspace-angular/pull/3327#pullrequestreview-2792622116. Kindly review and close the change requested.

2026-03-06 06:23 UTC, PitbaranK approved these changes

2026-05-08 21:46 UTC, tdonohue commented
Closing as this has been solved now in #5296.  Thanks for your contribution @im-shubham-vish to DSpace.  Unfortunately, a different approach was accepted into the codebase.  If you find any missing features in that approach, you are welcome to submit a follow-up PR.

2026-05-08 21:46 UTC, closed without merging