ORCID Login flow for private emails
DSpace/dspace-angular pull request #3355
Opened 2024-09-25 08:28 UTC by vins01-4science

#### _Please note that this development has been funded by the [ORCID Global Participation Fund](https://info.orcid.org/global-participation-program/global-participation-fund/)._
---

dspace-7_x version DSpace/dspace-angular#3349
dspace-8_x version DSpace/dspace-angular#3347

## References
* Fixes DSpace/DSpace#9087
* Related to DSpace/RestContract#294
* Requires DSpace/DSpace#9849

## Description
Reference the description on DSpace/dspace-angular#3347

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-03-05 22:47 UTC, tdonohue commented
@vins01-4science : Can you please rebase this so that it is testable again?  It currently has code conflicts.

2025-03-06 22:56 UTC, tdonohue requested changes
@vins01-4science : Thanks for this work! I gave this a code review today (as I'm not able to test it -- it still has merge conflicts).  Overall, the code looks reasonable, but there are some files which may have been accidentally added to this PR.  There's also some minor bugs that I can see via code review (i18n keys missing from `en.json5`), and other minor things.

2025-03-06 22:56 UTC, tdonohue commented on src/app/core/auth/auth-request.service.ts
> +  public postToMachineTokenEndpoint(): Observable<RemoteData<MachineToken>> {
I don't understand what these endpoints are. I didn't see any mention of `machinetokens` in the backend PR or REST Contract PR (https://github.com/DSpace/RestContract/pull/294)?  Is this an accidental change from some other feature?

2025-03-06 22:56 UTC, tdonohue commented on src/app/core/auth/models/machine-token.model.ts
> +export class MachineToken implements CacheableObject {
Again, I'm a bit confused how these machinetokens relate to this feature. I don't see mention of them in the backend PR (unless I'm missing it?)

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/confirm-email/confirm-email.component.html
> +    <input
For accessibility, all inputs should have a `label`. This appears to be missing a label.

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/confirm-email/confirm-email.component.ts
> +export class ConfirmEmailComponent implements OnInit, OnDestroy {
Please describe this component with a comment or TypeDocs.

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/confirmation-sent/confirmation-sent.component.ts
> +export class ConfirmationSentComponent { }
While I realize this is a small component, all components should have a description in a comment or TypeDocs. It's just useful for other developers to more easily understand the purpose of each component

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/provide-email/provide-email.component.html
> +    <input
Again, this input field needs a label

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/provide-email/provide-email.component.html
> +      placeholder="Input box"
Can we either remove the placeholder or make it a translatable string?

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/provide-email/provide-email.component.spec.ts
> +  // it('should call externalLoginService.patchUpdateRegistration when form is submitted with valid email', () => {
Is there a reason this test is commented out?  It seems like this is the main test for this component.  Can we uncomment it & fix it?

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/email-confirmation/provide-email/provide-email.component.ts
> +export class ProvideEmailComponent implements OnDestroy {
Again, all components should have a description in a comment or typedocs

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/external-log-in/external-log-in.component.html
> +    <h4 class="mt-2">or</h4>
This looks to be untranslated.   It probably should have an i18n key.  (Though I admit I'm not understanding why "or" is a header because I haven't been able to test this yet. It seems odd to me that this would be a header, as it doesn't seem like useful information)

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/external-log-in/external-log-in.component.html
> +    <button type="button" class="btn btn-outline-primary btn-sm" (click)="c('Close click');clearRedirectUrl()">
What is this "Close click"?  Is this accidental or maybe just for testing purposes?

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/external-log-in/external-log-in.component.ts
> +export class ExternalLogInComponent implements OnInit, OnDestroy  {
Again, it'd be good to give a description of the purpose of this component as a code comment / typedocs.

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/guards/registration-token.guard.spec.ts
> +    describe('when no token provided', () => {
Can we add a third test scenario of passing an *invalid* token?

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/registration-types/orcid-confirmation/orcid-confirmation.component.html
> +  <input [attr.aria-label]="'netId' | translate"
Why are we passing a literal string of `netId` to translate?  Shouldn't this be an i18n key?

This field also looks to be missing a `label`?  We might consider just adding a corresponding `<label>` instead of the `aria-label`.

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/registration-types/orcid-confirmation/orcid-confirmation.component.html
> +  <label class="font-weight-bold mb-0">{{"Last name" | translate}}</label>
Again, we are using literal strings here (and in more fields below).  It looks like we need to add the missing i18n keys.

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/registration-types/orcid-confirmation/orcid-confirmation.component.ts
> +export class OrcidConfirmationComponent extends ExternalLoginMethodEntryComponent implements OnInit  {
Again, please describe the component in comments / typedocs

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-log-in/services/external-login.service.ts
> +export class ExternalLoginService {
Again, please describe new service with a comment / typedocs

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-login-page/external-login-page.component.ts
> +export class ExternalLoginPageComponent implements OnInit {
Again, please add a description of the component

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-login-review-account-info-page/external-login-review-account-info-page.component.ts
> +export class ExternalLoginReviewAccountInfoPageComponent implements OnInit {
Same here, please add a description of the component.

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-login-review-account-info-page/review-account-info/review-account-info.component.ts
> +export class ReviewAccountInfoComponent implements OnInit, OnDestroy {
Again, please describe purpose of component

2025-03-06 22:56 UTC, tdonohue commented on src/app/external-login-review-account-info-page/review-account-info/review-account-info.component.ts
> +  notApplicableText = 'N/A';
We may want to make this an i18n key, as I don't know that "N/A" means the same thing in all languages.

2025-03-06 22:56 UTC, tdonohue commented on src/app/shared/external-log-in-complete/registration-types/orcid-confirmation/orcid-confirmation.component.scss
I'm confused why all these empty SCSS files seem to be in their own directories (alongside nothing else).  Were these accidentally added?

2025-03-06 22:56 UTC, tdonohue commented on src/assets/i18n/it.json5
> +  // "external-login.confirmation.header": "Information needed to complete the login process",
All the i18n keys starting from here & below have only been added to `it.json5`.  They are missing from `en.json5`.  They need to be copied or moved over to `en.json5`, otherwise the interface will not work in English.

2025-03-07 18:37 UTC, vins01-4science commented on src/app/external-log-in/external-log-in/external-log-in.component.html
> +    <button type="button" class="btn btn-outline-primary btn-sm" (click)="c('Close click');clearRedirectUrl()">
Is sent to the method `ModalRef#close(result?:any)` of the modal. Has been set like that just to register the event.

2025-03-07 20:24 UTC, vins01-4science commented
Hello @tdonohue , thank you for the review.
Could you re-review my latest changes?

2025-03-11 19:33 UTC, tdonohue commented
NOTE: This PR has merge conflicts caused by the merger of #3997.  You will need to rebase this PR on the latest `main` and update it to use ["control flow" syntax](https://angular.dev/guide/templates/control-flow) by replacing any `ngIf`, `ngFor`, or `ngSwitch` usages in HTML templates with `@if`, `@for` or `@switch`.  See the control flow docs or the above PR for more details.

2025-03-12 11:27 UTC, artlowel requested changes
Thanks @vins01-4science!

It all seems to work. A few points of feedback though:

#### 1. External login style
The external-login callback page looks messy:
![Screenshot 2025-03-12 at 11 25 12](https://github.com/user-attachments/assets/f1645d4f-fbe6-4349-977b-bac7ee336eeb)

That info alert looks like it's in a `row`, but not a `col` which is why it's lacking margins. When you don't need columns you can also simply leave out the row class to prevent that issue

#### 2. Email buttons
The look of that send verification link button can also be improved. I'd either put it in line with the input, or add some spacing between it and the input, and make it the exact same width.

The confirm email button has the same issue:
![Screenshot 2025-03-12 at 12 05 40](https://github.com/user-attachments/assets/5c62c3f4-ec99-4e02-affd-253dbf0a43ff)

#### 3. No alternative authentication methods
When ORCID is the only authentication method, you get an empty modal if you click the connect to existing user button:
![Screenshot 2025-03-12 at 11 27 23](https://github.com/user-attachments/assets/29491376-1de7-4461-931c-a647201d0f4a)

That button probably should just be left out if there are no alternative authentication methods

#### 4. Review confirmation modal
Finally on the review page, if you save you get this popup:
![Screenshot 2025-03-12 at 12 12 06](https://github.com/user-attachments/assets/f2420cd7-f477-4059-bc18-5f719c6fa65d)

… which was a bit confusing when I first saw it. As it's basically a confirmation modal, I'd change the contents to say something along the lines of "Are you sure you want to save the changes to your profile?". 

But then I'm not convinced we need a confirmation modal here. You could also just leave it out.

2025-03-12 19:16 UTC, vins01-4science commented
> Thanks @vins01-4science!
> 
> It all seems to work. A few points of feedback though:
> 
> #### 1. External login style
> The external-login callback page looks messy: ![Screenshot 2025-03-12 at 11 25 12](https://private-user-images.githubusercontent.com/1567693/421833343-f1645d4f-fbe6-4349-977b-bac7ee336eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDY3MjUsIm5iZiI6MTc0MTgwNjQyNSwicGF0aCI6Ii8xNTY3NjkzLzQyMTgzMzM0My1mMTY0NWQ0Zi1mYmU2LTQzNDktOTc3Yi1iYWM3ZWUzMzZlZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTJUMTkwNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk2YWYzM2I3NzgzNTZhYWJkZWQxZDY5YTc1MGQyNDg1Njc0NGExMmFhMzQ4ZmQxZWViNDlkY2U4M2ZjOGE2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yqz1KYSMPRYrdUnSOFriuVllDuTBVFvjYrw3MMYe73k)
> 
> That info alert looks like it's in a `row`, but not a `col` which is why it's lacking margins. When you don't need columns you can also simply leave out the row class to prevent that issue
> 
> #### 2. Email buttons
> The look of that send verification link button can also be improved. I'd either put it in line with the input, or add some spacing between it and the input, and make it the exact same width.
> 
> The confirm email button has the same issue: ![Screenshot 2025-03-12 at 12 05 40](https://private-user-images.githubusercontent.com/1567693/421854879-5c62c3f4-ec99-4e02-affd-253dbf0a43ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDY3MjUsIm5iZiI6MTc0MTgwNjQyNSwicGF0aCI6Ii8xNTY3NjkzLzQyMTg1NDg3OS01YzYyYzNmNC1lYzk5LTRlMDItYWZmZC0yNTNkYmYwYTQzZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTJUMTkwNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDE3YTkyODAzODEyODZhM2FiMTNkYzZjYTRhMjgwNGY1YzAyNzA3MjlkMmVlNGY0OWJmNzVkMWM4NjZjMmIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XIbNHSRlLLyHWgnHshvOPXT9190JImmoarHpp4xdN0Y)
> 
> #### 3. No alternative authentication methods
> When ORCID is the only authentication method, you get an empty modal if you click the connect to existing user button: ![Screenshot 2025-03-12 at 11 27 23](https://private-user-images.githubusercontent.com/1567693/421834286-29491376-1de7-4461-931c-a647201d0f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDY3MjUsIm5iZiI6MTc0MTgwNjQyNSwicGF0aCI6Ii8xNTY3NjkzLzQyMTgzNDI4Ni0yOTQ5MTM3Ni0xZGU3LTQ0NjEtOTMxYy1hNjQ3MjAxZDBmNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTJUMTkwNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE5YmQ4NWY5ZmZhNjM3MDcxMGQwYWVhZDA1OTNlNzUwOWNkYjZhMzdmYzA4NzUwNzc2ZGMyYmNjODY5ZDBjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PqknsqGEiF2U5BgqM5wQnCtQ9PlhuqQes_tNzK-JrNo)
> 
> That button probably should just be left out if there are no alternative authentication methods
> 
> #### 4. Review confirmation modal
> Finally on the review page, if you save you get this popup: ![Screenshot 2025-03-12 at 12 12 06](https://private-user-images.githubusercontent.com/1567693/421854767-f2420cd7-f477-4059-bc18-5f719c6fa65d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDY3MjUsIm5iZiI6MTc0MTgwNjQyNSwicGF0aCI6Ii8xNTY3NjkzLzQyMTg1NDc2Ny1mMjQyMGNkNy1mNDc3LTQwNTktYmMxOC01ZjcxOWM2ZmE2NWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTJUMTkwNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA5MmRjMzNjZTUzMzNhZjczNmIwOTgzZmRkZDFjMTA1MDU4YWRhZWI3ZTE5OGQxYTg4OGIxY2YxN2JkN2JlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.C6W3av1dZU_a_ROd-YPGcOHH5Isduyakk-mAu3GUl4E)
> 
> … which was a bit confusing when I first saw it. As it's basically a confirmation modal, I'd change the contents to say something along the lines of "Are you sure you want to save the changes to your profile?".
> 
> But then I'm not convinced we need a confirmation modal here. You could also just leave it out.

Thank you for the review @artlowel .

I've resolved all the issues you've found:

#### 1.
The external-login page UI has been improved as suggested:
![image](https://github.com/user-attachments/assets/f703c98e-280a-4e16-9b9b-a9d0d7e03784)

#### 2.
Placed more spacing between those elements and made the button full-width, as suggested:
![image](https://github.com/user-attachments/assets/1829a5d5-508b-46c8-bfbb-5f2b7da70441)

#### 3.
When no alternative login methods are found, the button won't be displayed
![image](https://github.com/user-attachments/assets/4e3ff771-43a9-4c05-93b5-cd29d491e578)

#### 4.
![image](https://github.com/user-attachments/assets/b6d248d3-3f2e-4b50-9d0e-c907b994c2ce)
Now it's a confirmation modal, as you suggested.

---

Let me know if you find something else.

2025-03-20 16:55 UTC, artlowel approved these changes
Thanks @vins01-4science!

2025-03-26 19:53 UTC, tdonohue approved these changes
👍 Thanks @vins01-4science !  As noted in my [backend review](https://github.com/DSpace/DSpace/pull/9849#pullrequestreview-2718469232), I tested/re-reviewed this today.  It's all working as expected (see my other review). 

As this is all at +2 (from @artlowel 's frontend review & testing of both), I'll merge this immediately.  After merger, it requires documentation to be added to the 9.0 docs (as stated in my other review)

2025-03-26 19:53 UTC, merged