Make reorder buttons keyboard accessible
DSpace/dspace-angular pull request #3372
Opened 2024-09-30 15:10 UTC by AndreaBarbasso

## References
* Fixes #1271

## Description
Added keyboard controls for drag and drop functionality on submission forms. The functionality follows the indications found [here](https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09#0303).

## Instructions for Reviewers
This PR can be tested by going in any submission form with repeatable fields.
Tabbing until the first drag element, an Aria assertive message is added to the live region, giving the user some instructions on how to reorder elements.
Elements can be reordered by pressing spacebar (activating the "drag" action), moving the item with the arrow keys, and then dropping the item again with the spacebar.
The Aria assertive message is always updated with info on the element being dragged and its current position.

List of changes in this PR:
* Added keyboard controls to drag and drop elements;
* Added Aria messages to the Live region.

## Checklist

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-01-23 09:43 UTC, AndreaBarbasso commented
@tdonohue, conflicts have been resolved!

2025-01-28 13:36 UTC, AndreaBarbasso commented
@artlowel, I implemented the changes you requested!

2025-01-29 18:05 UTC, tdonohue requested changes
@AndreaBarbasso : This looks great overall & works.  Overall, I'm +1

However, along with the spacebar, I'd like us to add the "Enter" key as another way to select the row.  That way this reorder feature works the same as the reordering of Bitstreams on the "Edit Item > Bitstreams" screen (see #3464).  (I initially tried to test this by pressing "Enter" and was surprised when I couldn't get it to work.  I then realized that it only responds to spacebar)

This PR also has a very minor code conflict in `en.json5` that needs to be resolved before merger.

2025-01-30 09:20 UTC, AndreaBarbasso commented
@tdonohue, I updated the PR! Merge conflicts have been resolved, and now the drag and drop can be toggled with the Enter key (in addition to the spacebar).

2025-01-30 09:42 UTC, artlowel approved these changes
Thanks @AndreaBarbasso!

2025-01-30 17:11 UTC, tdonohue approved these changes
👍 Thanks @AndreaBarbasso !  This looks great to me now too.  I retested and verified that you can also use the "Enter" key to select/deselect items for drag & drop reorder

2025-01-30 17:11 UTC, merged

2025-01-30 17:45 UTC, tdonohue commented
@AndreaBarbasso : I was able to successfully port this to 8.x in #3927.  However, my direct port to 7.x was unsuccessful (see #3928) because it appears this isn't as easy to adapt to that release.  (I've closed that PR because it doesn't work)

Would you be able to look into a way to port this to 7.x for the 7.6.3 release?  I'm not sure if I'll have time myself to adapt this to 7.x simply because I'm helping test several other PRs.  But, I'd love to see this also make it into 7.6.3