Accessibility in the statistics table
DSpace/dspace-angular pull request #3380
Opened 2024-10-02 16:31 UTC by Andrea-Guevara

## References
* Fixes #3300

## Description
Creation of a method that conditionally defines a dynamic label for the object column.

## Instructions for Reviewers
List of changes in this PR:
* The “getObjectHeaderLabel” method has been created to conditionally set a label to the column of objects.
* To differentiate between the label and the content, the two labels have been defined in the html using “<th scope=”col"></th>" and the "td" tag has been used for the content.
* New translation keys have been added in english, portuguese and spanish.

**Include guidance for how to test or review your PR.**
1. Go to the statistics area and see that the table now has a label for each column.
![Screenshot_9](https://github.com/user-attachments/assets/3e0aa970-8fcc-4ab5-8ecc-d8bd524b844d)

## Checklist
- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-10-03 14:21 UTC, Andrea-Guevara commented
Good morning @tdonohue!

I confess that I still need to improve a lot in relation to unit tests.

At first I went back to the tags that were being used. 

As I did this implementation using localhost, and I don't have geoIp configured to get a more detailed report on the statistics; I would like to ask that the person who is going to test this implementation try to do it in a more complete way, with more than one statistics table if possible. This is to test the dynamic behavior of the new label.

2025-01-24 18:20 UTC, tdonohue requested changes
@Andrea-Guevara : I gave this PR a code review today.  Overall, the code looks good, but I have a minor suggestion below.  Also, this currently has Merge Conflicts, so it's not in a testable state.  Could you resolve those merge conflicts please?

2025-01-24 18:20 UTC, tdonohue commented on src/app/statistics-page/statistics-table/statistics-table.component.ts
> +        return this.translateService.instant('statistics.table.header.TotalVisits');
I think you can get rid of this entire `switch` if you just append the `reportType` similar to this:

```
return this.translateService.instant('statistics.table.header.' + reportType);
```

That way, if new reports are added, we don't need to add more cases to this switch.

2025-01-30 15:53 UTC, Andrea-Guevara commented
Good afternoon @tdonohue! Sorry for the delay in replying, I hadn't seen your message.

I've resolved the conflicts and refactored the code according to your suggestion. I really appreciate your suggestions for improving the pulls. I've learned a lot from you over the last few days. Thank you very much.

The test is giving an error, but it seems that some configuration is different.

2025-01-30 16:22 UTC, tdonohue commented on src/app/statistics-page/statistics-table/statistics-table.component.spec.ts
> +      expect(component.getObjectHeaderLabel('UnknownType')).toEqual('');
This is where your tests are failing.  It looks like you previously were expecting `getObjectHeaderLabel()` to return an empty string if you passed it an unrecognized type.  

This isn't going to work the same anymore, because you are always just returning `statistics.table.header.[type]` in the code in `getObjectHeaderLabel()`.  So, I think you can just remove this test... all types will now be looked up in the i18n files.  This seems appropriate though because it allows for adding new report types without having to modify your code.

2025-08-27 21:05 UTC, tdonohue commented
Closing, replaced by #4661

2025-08-27 21:05 UTC, closed without merging