Accessibility when selecting a search filter
DSpace/dspace-angular pull request #3385
Opened 2024-10-04 12:09 UTC by Andrea-Guevara

## References
* Fixes #3299

## Description
Creation of a method which, when a search filter is clicked, announces to the user that the page will be reloaded and which filter has been selected.

## Instructions for Reviewers
List of changes in this PR:
* In the component “search-facet-option.component” the method “selectingFilter()” has been created which, making use of the services “LiveRegionService” and “TranslateService”, creates a message which, as soon as the search filter is clicked, announces to the user that the page will be reloaded and which filter is being applied.
* The “filterService.minimizeAll()” method that used to be called directly in the html is now called in the new method that has been created and is applied after the reload message is announced.
* New translation keys have been added.

**Include guidance for how to test or review your PR.**
1. Go to the search area where the filters are applied https://sandbox.dspace.org/search?query=;
2. Using a screen reader, select a filter and notice that a page reload message is announced.

## Checklist
- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-01-09 14:41 UTC, nwoodward commented
Good morning @Andrea-Guevara. This PR looks good. Can you fix the conflicts in the translations files?

2025-01-09 15:04 UTC, Andrea-Guevara commented
Good morning @nwoodward! done

2025-01-09 16:39 UTC, nwoodward commented
@Andrea-Guevara Thanks! There's just one lint error in the tests. You can run `npm run lint-fix` to fix it. That should move the import of `LiveRegionService` up in the list of imports in `search-facet-option.component.ts`, and then the tests should pass. 🤞

2025-01-10 19:33 UTC, Andrea-Guevara commented
Good afternoon @nwoodward!
I'm stopping by to inform you that, in my work environment, it's a bit complicated to solve these small problems using “npm run lint-fix”. It always gives some error with the plugin. But as soon as I can solve it, I will! Have a good weekend

2025-01-14 16:50 UTC, Andrea-Guevara commented
Good afternoon @nwoodward, I hope you're well!

Unfortunately I haven't been able to solve the import sorting error. I've tried several ways and even created a new pull to see if it worked, but it didn't :(

https://github.com/DSpace/dspace-angular/pull/3841

2025-01-23 20:12 UTC, Andrea-Guevara commented
Thank you very much for your help @nwoodward!

2025-01-24 17:35 UTC, tdonohue requested changes
@Andrea-Guevara : I gave this a quick code review today.  Overall, the code looks reasonable, but I have some recommendations for how you could simplify your code (and avoid possibly using `subscribe`, as I don't believe it's needed here).  See below.

(I haven't had a chance to test this yet, but I'll do so once the code is updated.)

2025-01-24 17:35 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "search-facet-option.update.announcement": "The page will be reloaded. selected filter: ",
We should add a placeholder for the filter to this message.  This can be changed to be something like:
```
"search-facet-option.update.announcement": "The page will be reloaded. Filter {{ filter }} is selected.",
```

That allows us to avoid having to append the filter name later on..and it will clean up your other code.  See my next comment

2025-01-24 17:35 UTC, tdonohue commented on src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts
> +        .subscribe(translatedMessage => {
I *think* you can avoid doing this entire `subscribe` by following the same code structure as other components which use the LiveRegionService.  For example, see item-bistreams.service.ts: https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.ts#L521-L525

If you follow that example, I think you can simplify all your code here to be something like this:
```
const message = this.translateService.instant('search-facet-option.update.announcement',
      { filter: filterValue });
this.liveRegionService.addMessage(message);
```

2025-01-24 17:35 UTC, tdonohue commented on src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts
> +          setTimeout(() => {
I'm not sure I understand why you have to call `setTimeout` here.  It's already set by the `liveRegionService.addMessage()` call.   If there's a reason for this section of code, then I'd recommend describing it with a code comment.  Currently, it looks odd to me because I don't see any other areas in our current code where we call `setTimeout()` for a Live Region.

2025-01-24 17:37 UTC, nwoodward approved these changes
Thanks @Andrea-Guevara! I tested this PR locally, and it adds the user notification to the live region that the page will reload.

2025-01-27 17:32 UTC, Andrea-Guevara commented
Good afternoon @tdonohue! I really took an unnecessary turn when building this code. I followed your suggestions and updated the code. The setTimeout() was to clear the message faster. If we select a new filter followed by another, the message from the first filter is repeated. But after a while this no longer happens!

Looking forward to your feedback

2025-01-29 16:09 UTC, nwoodward approved these changes
👍 I tested this again today, and it still functions as described. The reloading message appears in the live region where it's read by a screen reader and stays around for a bit.

2025-01-29 16:48 UTC, tdonohue approved these changes
👍 Thanks @Andrea-Guevara !  I gave this a quick test via NVDA screen reader and I can verify that the text added to the live region is read out when selecting a search filter.  Looks good now!

2025-01-29 16:52 UTC, merged

2025-01-29 17:07 UTC, tdonohue commented
@Andrea-Guevara : I was able to port this to 8.x (for 8.1).  However, I'm running into issues porting it to 7.x (`dspace-7_x` branch) because the code for search filters/facets is quite different in 7.x.   If you have time to port this to `dspace-7_x` branch (in a different PR), it would be good to do so.  

In the meantime, I'll just mark this as **only fixed in 8.1 and 9.0**

2025-01-30 13:08 UTC, Andrea-Guevara commented
Good morning, I've made a pull available in version 7, but it failed the tests. I investigated a bit and it seems that it is related to the code structure of the "search-facet-option" component and the “LiveRegionService” service.

2025-01-31 15:29 UTC, tdonohue commented
Ported to 8.x in #3918 and to 7.x in #3926