Enforce DSpace-specific coding conventions
DSpace/dspace-angular pull request #3390
Opened 2024-10-07 10:36 UTC by alexandrevryghem

## References
* Fixes #3265

## Description
Introduced 5 new ESLint rules to enforce coding conventions that we already apply to most of the code. This work is based on the new linting rules introduced in #2865.

## Instructions for Reviewers
A total of 5 new rules were created:
- `dspace-angular-ts/alias-imports`: This rule enforces aliased imports like `import { of as observableOf } from 'rxjs';`
- `dspace-angular-ts/themed-decorators`: This rule enforces that every entry component decorator in the `themes` folder contains a theme name.
- `dspace-angular-ts/themed-wrapper-no-input-defaults`: This rule enforces that `ThemedComponent` wrappers do not set default values on inputs (see #2164). This rule doesn't have an auto-fix function by default since, if the type of the `@Input()` is missing, we would have to make a guess, which could lead to an incorrect value being set. An example of this would be `@Input() title = null;`, which we would incorrectly transform into `@Input() title: null;`.
- `dspace-angular-ts/unique-decorators`: This rule enforces that entry component decorators are not duplicated.
- `dspace-angular-ts/sort-standalone-imports`: This rule enforces that standalone imports are sorted alphabetically, and enforces them to be on multiple lines for easier merge conflict resolution

**Guidance for how to test and review this PR:**
- Run `npm run lint-fix -- --quiet` and verify that all the new rules automatically fix the linting issues except for `dspace-angular-ts/themed-wrapper-no-input-defaults`.
- Verify that the code and the tests still work as they did before.
- Update the `.eslintrc.json` file locally to enable the `dspace-angular-ts/sort-standalone-imports` rule as well since I temporarily disabled it to prevent too many conflicts

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-03-12 18:07 UTC, alexandrevryghem commented
I added a new custom linting rule as well to sort the standalone imports alphabetically which also enforces imports to be on separate lines. Currently I disable this rule and haven't committed the lint fixes for this rule, since it would cause continuous merge conflicts, but I'll enable it again right before the PR gets merged.

2025-03-12 19:07 UTC, ybnd requested changes
Approved, save for a few small suggestions below.

@tdonohue I did some of the initial work this PR was based on, so it's probably best if someone else can provide some input too

2025-03-12 19:07 UTC, ybnd commented on .eslintrc.json
> +            "indent": "  ",
Could you change the indent to a number of spaces to match ESLint's `indent` rule?

2025-03-28 10:24 UTC, ybnd approved these changes
All good now, thanks!

2025-04-10 13:36 UTC, atarix83 requested changes
thanks @alexandrevryghem for this PR

I generally agree with the rules added, except for the one enforcing the use of `observableOf`. it was the old name for the `of` operator, which is no longer used. Personally, I don't see the reason to use the alias instead of the shorter name. Furthermore, if we establish an alias for the `of` operator, we should also apply aliases to other creation operators like `from`, among others.

If the objective of the rule is to achieve tidier code, it would be more logical to set the rule in the opposite direction, so we always use the current operator name.

2025-04-21 23:14 UTC, alexandrevryghem commented
@atarix83: I added some logic to enforce disallowing aliased imports for `import { of } from 'rxjs'`. I also auto fixed the  imports for the new standalone imports rule

2025-05-15 13:07 UTC, atarix83 approved these changes
thanks @alexandrevryghem 

LGTM. It needs a rebase with main branch

2025-05-15 15:44 UTC, tdonohue commented
@alexandrevryghem : Apologies for the code conflicts, but I'm still planning on merging this for 9.0.  If you can rebase & fix the code conflicts, I'll make sure this gets merged either today or tomorrow.

2025-05-15 16:21 UTC, alexandrevryghem commented
@tdonohue: No worries, I'll keep an eye on this PR tomorrow evening to rebase it before the merge

2025-05-16 16:04 UTC, tdonohue commented
@alexandrevryghem : Can you rebase this PR (and update to latest main) one last time?  Everything else that I plan to merge for 9.0 has been merged.  So, this will be the last thing to get in once it is ready.

2025-05-16 16:23 UTC, alexandrevryghem commented
@tdonohue done

2025-05-16 17:29 UTC, tdonohue commented
@alexandrevryghem : Strangely, if I use this PR and run `npm run lint` locally on a Windows 11 machine, I get a report of 15 lint errors.  Here's a sample of what I see:

```
C:\dspace-angular\src\themes\custom\app\entity-groups\journal-entities\item-pages\journal-issue\journal-issue.component.ts
  18:80  error  There is a theme declaration in decorator, but this file is not part of a theme  dspace-angular-ts/themed-decorators

C:\dspace-angular\src\themes\custom\app\entity-groups\journal-entities\item-pages\journal-volume\journal-volume.component.ts
  18:81  error  There is a theme declaration in decorator, but this file is not part of a theme  dspace-angular-ts/themed-decorators
```

If I run `npm run lint-fix` to attempt to fix them, I see changes like this being made:
```
--- a/src/themes/custom/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.ts
+++ b/src/themes/custom/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.ts
@@ -15,7 +15,7 @@ import { listableObjectComponent } from '../../../../../../../app/shared/object-
 import { ThemedResultsBackButtonComponent } from '../../../../../../../app/shared/results-back-button/themed-results-back-button.component';
 import { ThemedThumbnailComponent } from '../../../../../../../app/thumbnail/themed-thumbnail.component';

-@listableObjectComponent('JournalIssue', ViewMode.StandalonePage, Context.Any, 'custom')
+@listableObjectComponent('JournalIssue', ViewMode.StandalonePage, Context.Any)

--- a/src/themes/custom/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.ts
+++ b/src/themes/custom/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.ts
@@ -15,7 +15,7 @@ import { listableObjectComponent } from '../../../../../../../app/shared/object-
 import { ThemedResultsBackButtonComponent } from '../../../../../../../app/shared/results-back-button/themed-results-back-button.component';
 import { ThemedThumbnailComponent } from '../../../../../../../app/thumbnail/themed-thumbnail.component';

-@listableObjectComponent('JournalVolume', ViewMode.StandalonePage, Context.Any, 'custom')
+@listableObjectComponent('JournalVolume', ViewMode.StandalonePage, Context.Any)
```

I'm also seeing this error which isn't fixable by `lint-fix`
```
C:\dspace-angular\src\themes\custom\app\shared\object-list\sidebar-search-list-element\item-types\publication\publication-sidebar-search-list-element.component.ts
  15:2  error  Duplicate decorator call  dspace-angular-ts/unique-decorators
  16:2  error  Duplicate decorator call  dspace-angular-ts/unique-decorators
  17:2  error  Duplicate decorator call  dspace-angular-ts/unique-decorators
  18:2  error  Duplicate decorator call  dspace-angular-ts/unique-decorators
```

Is this something specific to Windows?  It's strange to me that these errors do NOT occur in GitHub actions (obviously), but I'm seeing them locally, and there are changes

2025-05-16 18:37 UTC, tdonohue commented
@alexandrevryghem : If I run `npm run lint` again in the same tab *or* a different tab, I get the same 15 lint errors every time.

The first 11 errors are all say `There is a theme declaration in decorator, but this file is not part of a theme  dspace-angular-ts/themed-decorators`  (and these are the ones that can be fixed by running `npm run lint-fix`)

The last 4 errors are the ones displayed above, which say: `Duplicate decorator call  dspace-angular-ts/unique-decorators`

2025-05-16 18:44 UTC, tdonohue commented
@alexandrevryghem : If this isn't immediately/quickly fixable, I think it's OK to figure this out on Monday.  I realize it must be very late for you.  

Since this PR already is at +2, I think we can give it an extra day to get it cleaned up for 9.0.   I just want to be sure that running `npm run lint` on Windows also works before we merge it.

2025-05-16 19:01 UTC, alexandrevryghem commented
@tdonohue: I'm trying to setup DSpace on my Windows computer but it's taking a while so if you're fine to wait until Monday that's fine by me. Otherwise I can simply disable the rule, so that you can merge this PR already, and I'll try to open a PR with a fix for this later

2025-05-16 19:05 UTC, tdonohue commented
@alexandrevryghem : I'm fine with the extension until Monday.  Let's just see if we can get it figured out on Monday.  If not, disabling the rule for now is OK until it can be resolved.

2025-05-16 19:49 UTC, alexandrevryghem commented
@tdonohue: I finally was able to set it up and it works fine on Windows for me 😬. I do remember that during the development of this lint rule there were some issues with IntelliJ as well, and to fix this I sometimes had to restart the whole application. I'll already disable the rule for now since I'm not sure how fast I will be able to create a fix for this issue

2025-05-16 21:03 UTC, tdonohue approved these changes
👍 Thanks @alexandrevryghem !  This looks good to me now that the problematic tests are disabled.  We can work to get those fixed up once we narrow down the issue I'm encountering

2025-05-16 21:03 UTC, merged