Accessibility settings page
DSpace/dspace-angular pull request #3613
Opened 2024-11-06 13:45 UTC by AAwouters

## References
Backend PR: [Accessibility settings metadata field 9964](https://github.com/DSpace/DSpace/pull/9964)
8_x backport: [TODO]
7_x backport: [TODO]

Fixes point 3 of #1191: "Content visually appears and disappears with no ability to adjust timing."

## Description
This PR adds the 'Accessibility settings' page where a user can configure accessibility settings.  This page can be found either through the 'Accessibility settings' link in the footer, or through the link on the profile page. The settings are stored in a cookie when the user is not authorized and are stored in a metadata field (see backend PR) when the user is authenticated.

## Instructions for Reviewers
Access the page through one of the mentioned links, or directly at `/info/accessibility`. Currently only two settings are available: notification time-out and live region time-out. Functionality of the notification time-out is the easiest to verify. Set a new value and click the 'Save accessibility settings` button. A notification will appear mentioning whether the changes are saved locally (cookie) or on the user profile (metadata) and this notification will stay as long as configured.
Live region time-out can be verified by making the live region visible. (see #3337)

List of changes in this PR:
* Adds the `accessibility-settings` component and service
* Adds links to the 'Accessibility settings' page to the footer and profile page.
* Notifications added to the `notifications-board` will have the user-configured time-out (if set by the user).
* Messages added to the live-region will have the user-configured time-out (if set by the user).

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-12-19 17:46 UTC, nwoodward commented
Hi @AAwouters. Thank you for this PR. Overall, it looks really good. I tested it locally, and I'm having a problem with the Accessibility Settings form, both as an anonymous user and when I'm logged in. It happens on Firefox and Chrome.

When I change the "Hide notifications automatically" setting to off and click "Save accessibility settings" the green "Successfully saved settings..." notification doesn't go away until I click on the 'X'. That isn't a big problem, but once I change that setting then I can never change it back to on. Every time I do the setting returns to off, even though the green "Successfully saved settings" notification appears.

However, I am able to change the Notification and Live region timeouts successfully. The green "Successfully saved settings..." notification appears and disappears on its own. Also, clicking on "Reset accessibility settings" works well. And the green "Successfully reset settings" notification goes away after a few seconds. So I think the problem is only with the option to hide notifications automatically.

<img width="1367" alt="Screenshot 2024-12-19 at 11 10 34 AM" src="https://github.com/user-attachments/assets/0eb512ab-9da5-49c0-a3a1-1bf0e8894332" />
<img width="1343" alt="Screenshot 2024-12-19 at 11 13 37 AM" src="https://github.com/user-attachments/assets/5ebd8898-5514-40f0-b8bf-9bf1475ff16a" />

2025-01-23 09:19 UTC, AAwouters commented
@nwoodward 
> When I change the "Hide notifications automatically" setting to off and click "Save accessibility settings" the green "Successfully saved settings..." notification doesn't go away until I click on the 'X'.

Yes. When you disable automatic notification hiding, notifications won't hide/'go away' automatically. Maybe I misunderstood you but is that not exactly the expected behavior?

> once I change that setting then I can never change it back to on. Every time I do the setting returns to off, even though the green "Successfully saved settings" notification appears.

Right. That was a small oversight on my part. It should be fixed now.

2025-01-24 20:32 UTC, tdonohue requested changes
@AAwouters : Thanks for this PR.  Overall, the feature works, but I've run into a few bugs and areas for improvement.

1) If I open the "Accessibility settings", leave the defaults and click "Save accessibility settings" button, I see an error in my Browser's DevTools console.  This same error also appears if you try to change the time outs while anonymous.
```
TypeError: Cannot read properties of undefined (reading 'cookieExpirationDuration')
```
* I'm running the UI in production mode: `npm run build:prod; npm run serve:ssr`
* Do not login (stay anonymous)
* Go to the "Accessibility Settings" page
* Click the "Save Accessibility settings" button immediately.  Or try to change one of the two timeouts (without touching the toggle).
* In your browser's DevTools console, you'll see the error.

2) Both of the time-outs can be set to a negative number, which doesn't make sense.  I'd recommend we only allow a minimum of 1 or zero.

3) If you open the Accessibility Settings and immediately click the up or down arrow next to the default time outs, you'll jump to -1 or 1.  This is odd, especially for the "Live region time out", which starts at 30, but if you click the "up" arrow on the field, it goes to 1.

4) I'm not a fan of the current display.  I think we should change the labels to say "Notification time out (in seconds)" and "ARIA live region time out (in seconds)" as those are more accessible.  Having the word "Seconds" appear **after** the input field will not make sense to screen readers.  I also have a recommendation for renaming the "Hide notifications automatically" label (see comments inline below)

![accessibility-settings](https://github.com/user-attachments/assets/1249ecd2-b52e-4bc5-b6d3-b0f9cd273189)

I also have some general suggestions inline below.  Most of it is just text change suggestions.

2025-01-24 20:32 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "info.accessibility-settings.liveRegionTimeOut.label": "Live region time-out",
I think we should call this "ARIA live region time out (in seconds)".  These live regions are ARIA live regions: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

2025-01-24 20:32 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "info.accessibility-settings.liveRegionTimeOut.hint": "The duration after which a message in the live region disappears.",
I think we should give more information here. "The duration after which a message in the ARIA live region disappears. ARIA live regions are not visible on the page, but provide announcements of notifications (or other actions) to screen readers."

2025-01-24 20:32 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "info.accessibility-settings.notificationTimeOut.label": "Notification time-out",
Change to say "Notification time out (in seconds)".  There's no hyphen in "time out"

2025-01-24 20:32 UTC, tdonohue commented on src/app/accessibility/accessibility-settings.service.ts
> +export const ACCESSIBILITY_COOKIE = 'dsAccessibilityCookie';
We need to add this Cookie to our Orejime settings (in the "Cookie Settings" in the footer).  It should be possible to opt-out of having this cookie saved, as it's not required.

NOTE: In DSpace 8 and 7, this cookie will need to be added to the Klaro settings, as we only use Orejime as of DSpace 9.  But, the two are similar.

2025-01-24 20:32 UTC, tdonohue commented on src/app/info/accessibility-settings/accessibility-settings.component.html
> +        <input [type]="'number'" [id]="'notificationTimeOutInput'" class="form-control"
If possible, we should ensure this field cannot be set to zero or a negative number.  The minimum should be one second.

2025-01-24 20:32 UTC, tdonohue commented on src/app/info/accessibility-settings/accessibility-settings.component.html
> +        <input [type]="'number'" [id]="'liveRegionTimeOutInput'" class="form-control"
Same here. If possible, we should ensure this field cannot be set to zero or a negative number.  The minimum should be one second, otherwise we'd be disabling the ARIA live region.

2025-01-24 20:32 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "info.accessibility-settings.liveRegionTimeOut.unit": "Seconds",
I'd remove these "Seconds" keys, as they are not very accessible.  This should be part of the label itself, so that screen readers understand the input field is representing seconds.

2025-02-21 12:47 UTC, artlowel commented
@tdonohue Heads up: while I agree with your feedback. I should warn you that we're already quite a ways above the 100 hours that were the combined estimate on the original tickets (https://github.com/DSpace/dspace-angular/issues/1191, https://github.com/DSpace/dspace-angular/issues/1270 and https://github.com/DSpace/dspace-angular/issues/3154). Among other things because a separate accessibility settings page wasn't planned when we started. We're currently at 172 hours, and still have to start on the Orejime integration

2025-02-21 15:22 UTC, tdonohue commented
@artlowel : Thanks for letting us know.  Please also try to remember to ping @hostle83 on any updates of estimates.   

Could we have a fresh estimate then for how much time it anticipated for this entire effort?   I know @hostle83 is trying to keep track of how much money is left in our fund for fixing accessibility issues. So, a new total estimate would be helpful for fund tracking purposes.

2025-02-21 15:24 UTC, artlowel commented
@tdonohue @hostle83 It should be doable in 185 hours total

2025-02-25 18:06 UTC, hostle83 commented
> @tdonohue @hostle83 It should be doable in 185 hours total

Thank you, @artlowel!

2025-02-26 12:49 UTC, AAwouters commented
I've processed your feedback @tdonohue .

> If I open the "Accessibility settings", leave the defaults and click "Save accessibility settings" button, I see an error in my Browser's DevTools console.

I was not able to reproduce this issue. `cookieExpirationDuration` is a configuration property so is it possible that the `accessibility` configuration somehow is undefined in your configuration?
I did make a small change to how that value is retrieved (moved from using `environment` directly to injecting `APP_CONFIG`).

> Both of the time-outs can be set to a negative number, which doesn't make sense. I'd recommend we only allow a minimum of 1 or zero.

I initially wanted to avoid validation as it's a fairly simple form, but I agree that being able to enter negative values does not make sense.

> If you open the Accessibility Settings and immediately click the up or down arrow next to the default time outs, you'll jump to -1 or 1. This is odd, especially for the "Live region time out", which starts at 30, but if you click the "up" arrow on the field, it goes to 1.

The reason for this is that those numbers were placeholders based on the default values and not actual values in the form.
As there is no actual value in the input field, it starts at 1 or -1 depending on which arrow you click.

The reason I used those placeholders instead of filling the form with the default values is because the behavior is slightly different for notifications.
The time-out for a notification can be set upon creation of the notification, in case no time-out is provided the default is used.
With the addition of the accessibility settings, three cases are possible:
- Notification created without time out & no user-defined time out: Default time out is used.
- Notification created with time out & no user-defined time out: Provided time out is used.
- Notification created & there is a user-defined time out: user-defined time out is always used.

This means that when the default is pre-filled in the form and the user saves the form without making changes, the user might have changed the behavior without realising.
I suppose this is not that big of a deal as then all notifications will have the same time out.
It might even be possible that not a single notification is created with a different time out, but I did not check.

With the validation, empty fields are no longer possible so now the fields are filled with the default values (if there are no user-configured values yet).


#### e2e tests
With the addition of a new (optional) cookie, there are some issues with the e2e tests.
The cookie window sometimes covers elements such as buttons which causes the tests to fail.
For the `main` branch I've managed to fix the tests by simply clicking the 'accept' button of the cookie window in the necessary places.

For the `7_x` and `8_x` branches this approach does not seem to work.
It looks like the cookies are not cleared across tests so when a future test also attempts to click that same button, it fails to do so as it no longer exists.

Keep in mind that when logged in a different cookie is used based on the userId so three cookies are necessary: one for anonymous users, one for the admin user and one for the submitter user.
I've tried lots of things such as clearing and setting the cookies before each test, but I've had no luck so far.

2025-02-28 19:56 UTC, tdonohue requested changes
@AAwouters : Thanks for the updates.  I think this looks much better and is working well.  I just have a few _minor_ suggestions inline on how to cleanup the e2e tests (and fix those for 7.x and 8.x) and a few other minor things.

Once these minor things are cleaned up, I'd be +1 this PR.  Thanks!

2025-02-28 19:56 UTC, tdonohue commented on src/assets/i18n/en.json5
> +  "info.accessibility-settings.liveRegionTimeOut.hint": "The duration after which a message in the ARIA live region disappears. ARIA live regions are not visible on the page, but proivde announcement
Small typo here that I just noticed.  In the second sentence "proivde" should be "provide".

2025-02-28 19:56 UTC, tdonohue commented on src/app/footer/footer.component.html
> +             routerLink="info/accessibility">{{ 'footer.link.accessibility' | translate }}</a>
I think we should move this link next to the "Cookie Settings" in order to keep the two settings together.  So, I'd propose the footer list these links in this ordering...

"Cookie settings" "Accessibility settings" "Privacy Policy" "End User Agreement", "Send Feedback"

2025-03-07 13:04 UTC, AAwouters commented on cypress/e2e/collection-create.cy.ts
> +  cy.get('.orejime-Button--save').click();
I already tried adding the new setting in [this commit](https://github.com/DSpace/dspace-angular/pull/3613/commits/958b3b8c05c2228643e2be2f788c96d7eb899d8a).
In the meantime I've learned that when authenticated, the data is stored in a [different cookie based on the userId.](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/cookies/browser-orejime.service.ts#L197)
I tried adding those as well in [this commit](https://github.com/DSpace/dspace-angular/pull/3613/commits/a2882b064476950861f310ad1d24c0dd730b5eef).

Something else I noticed (on the `main` branch) is that the cookies are removed when logging in.
I've tried setting the cookies using `cy.setCookie` method after the login method, but it seems this is too late. The window already is visible by then.
On the `7_x` and `8_x` branches the cookies do not get removed when logging in.

One last thing I learned is that [the cookie data is stored in ePerson metadata](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/cookies/browser-orejime.service.ts#L344-L350) as well. Is it possible this is somehow related to the issues?

2025-03-07 14:49 UTC, tdonohue commented on cypress/e2e/collection-create.cy.ts
> +  cy.get('.orejime-Button--save').click();
@AAwouters : You could try setting the cookie in each of the test user's EPerson metadata.  I'm honestly not sure why this has started to fail with *this PR*, since the approach we use now has worked well on the `main` branch for a long time.  So, I suspect there's an accidental "side effect" in this PR, and it may be something specific to Orejime (used on `main`) and not impacting Klaro (used on `dspace-8_x` and `dspace-7_x`).  But, I'm not sure what it would be offhand.

Unfortunately, I may not have a chance to help look at this anytime soon, as I'm busy reviewing feature PRs before our 9.0 feature deadline.  However, once I'm done with that, I can revisit this PR if you still are looking for a solution.

2025-03-11 19:32 UTC, tdonohue commented
NOTE: This PR has merge conflicts caused by the merger of #3997.  You will need to rebase this PR on the latest `main` and update it to use ["control flow" syntax](https://angular.dev/guide/templates/control-flow) by replacing any `ngIf`, `ngFor`, or `ngSwitch` usages in HTML templates with `@if`, `@for` or `@switch`.  See the control flow docs or the above PR for more details.

2025-03-21 14:52 UTC, artlowel commented on cypress/e2e/collection-create.cy.ts
> +  cy.get('.orejime-Button--save').click();
The reason it starts to fail with this PR seems to be that in the docker db we're using for e2e tests, the test user already has a `dspace.agreements.cookies` metadata value, with this value
```json
{"authentication":true,"preferences":true,"acknowledgement":true}
```

This PR adds an additional option: [`accessibility`](https://github.com/DSpace/dspace-angular/pull/3613/files#diff-9e2257e310661c2e6a0c89a5889113b6d6acb86674c8cc31ba88635794d60fe3R194-R199). It is unset for the test user, which is why the popup shows up again.

So the solution is either to update the db we use for testing, so the popup is already accepted, or figure out a way to accept the popup after each login (which may be the preferred way, because that way we don't have to update the db the next time something is added)

2025-03-22 11:05 UTC, artlowel commented on cypress/e2e/collection-create.cy.ts
> +  cy.get('.orejime-Button--save').click();
I added [a command to click "accept" in the popup after every login](https://github.com/DSpace/dspace-angular/pull/3613/commits/33062214da02884fd3614355be298c4c04e7aa4b), and that seems to have fixed it

2025-03-22 11:18 UTC, artlowel commented on cypress/e2e/collection-create.cy.ts
> +  cy.get('.orejime-Button--save').click();
Oh I see that was @AAwouters' initial solution as well, I should've read the whole conversation first, I apologize. 

But, as I said above, setting the cookies from cypress doesn't work for registered users. The reason why it seemed to work before was because they already had a `dspace.agreements.cookies` metadata field with all the options accepted, and that takes precedence over the cookie. We could technically intercept or mock the request that retrieves the eperson to override that metadata field, but simply using cypress to click the cookie popup seemed a lot more straightforward.

2025-05-05 22:14 UTC, tdonohue commented
@AAwouters : Now that #4106 is resolved, I wonder if you could rebase this PR on `main` to see the current status of the e2e tests.  When I run the e2e tests in this PR **locally**, I'm finding that they **fail**.  But, I'm able to get them to succeed with a few minor changes:

1. First, I update the `cookieContent` variable in `e2e.ts` to be:
```
const cookieContent = '{"authentication":true,"preferences":true,"acknowledgement":true,"google-analytics":true,"matomo":true,"google-recaptcha":true,"accessibility":true}';
```
2. Then, I remove or comment out all usages of the new `cy.acceptOrejimePopup()` method.  As you noted, this only works if the popup exists, and with the new `cookieContent` settings, the popup no longer seems to occur (at least on my machine).  But, it would be best to see if that behavior also exists in GitHub Actions.

Regarding the other options you [mentioned above](https://github.com/DSpace/dspace-angular/pull/3613#issuecomment-2808978772), it currently is very difficult to add/update the default test data.  It *can be done*, but it will take at least a few hours each time we wish to change the stored data.  So, this isn't really a good long term solution, as it'd require changing the data anytime something new is added to Orejime.

I also do know that @AndreaBarbasso is hitting this same issue in #3889 as that adds another optional setting to Orejime.  So, if we can find a generic solution together, it would benefit both PRs.  The option to send a `POST` for all accounts (to save cookie data before the popup occurs) might be a solution we could investigate if the simple updates that I listed above don't work.

2025-05-15 15:40 UTC, tdonohue commented
@AAwouters : When you get a chance tomorrow, please rebase this against the latest `main` (and remove any remaining fixes in the PR related to Orejime in the e2e tests).  #3889 was just merged, and it now *disables* Orejime entirely in the e2e tests, so it should solve the issues you were seeing in this PR.

2025-05-16 08:15 UTC, AAwouters commented
@tdonohue All checks on this, and [the rest PR](https://github.com/DSpace/DSpace/pull/9964), have passed.
As #3889 is not ported to 8.x or 7.x I made no changes to the backports yet.

2025-05-16 12:09 UTC, tdonohue commented
@AAwouters : Regarding the backports, we were not planning to fully backport #3889 to 8.x and 7.x, as those releases did not use Orejime. From my understanding, the e2e test issues were specific to Orejime and didn't impact Klaro (at least that's what @artlowel mentioned in yesterday's Dev Meeting).   

If you are finding the same e2e failures in 8.x and 7.x, then we'd need to figure out a way to backport the configuration changes of #3889 also back to Klaro on 8.x and 7.x

But, for now, the biggest goal is to just get this fixed in 9.0.  We are not under as big of a rush to create the backports at this time

2025-05-16 14:34 UTC, tdonohue reviewed
@AAwouters and @artlowel : While not a "blocker", the help information on the new accessibility settings page is not entirely visible because it appears all the way to the right of the page.  See this screenshot as an example
![helpinfo](https://github.com/user-attachments/assets/12a20b1b-5c55-494b-8121-f222bc5e6cd1)

When the text is cut off like this, it's not possible to scroll to the right to see it all.
If we can simply move the question mark icons over closer to the fields, it should solve the problem.

Still testing today, but so far that's the only issue I've found

2025-05-16 14:39 UTC, tdonohue commented
@AAwouters and @artlowel : One last non-blocker, but might be nice to quickly fix.  The "Accessibility settings" link in the footer is slightly misaligned.  It's a few pixels *higher* than all the other links, which looks odd when you look closer.  Here's a zoomed in screenshot that shows it a bit better

![footer](https://github.com/user-attachments/assets/a009bbc7-56f9-4d1a-8dab-8003f036756c)

2025-05-16 14:42 UTC, tdonohue commented
@AAwouters and @artlowel : I've completed my testing.  This is working great, except for the two **minor issues** above.  See https://github.com/DSpace/dspace-angular/pull/3613#pullrequestreview-2846834683 and https://github.com/DSpace/dspace-angular/pull/3613#issuecomment-2886914891 

Nonetheless, I do think it'd be nice to fix those two minor issues if possible.  Would that still be possible to do today?

2025-05-16 15:29 UTC, tdonohue approved these changes
👍 Thanks @AAwouters !  This all looks good to me now & works well.  Once the automated tests finish passing, I'll merge this immediately.

2025-05-16 16:00 UTC, tdonohue commented
Merging for 9.0.  The backports will still be kept open though until we can "re-sync" them with this PR and, as necessary, resolve current failing e2e tests.  It's unclear to me if that will require also backporting #3889, or if another solution is possible.

2025-05-16 16:00 UTC, merged