Update fr.json5
DSpace/dspace-angular pull request #3673
Opened 2024-11-18 20:22 UTC by Peredwel

Ajouté des traductions/noté quelques étiquettes sans traductions

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #issue-number (if this fixes an issue ticket)
* Requires DSpace/DSpace#pr-number (if a REST API PR is required to test this)

## Description
Added translations/flagged some labels without translation for francophone DSpace

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-02-10 21:26 UTC, pilasou commented on src/assets/i18n/fr.json5
> +  "process.detail.delete.cancel": "",
This can be translated by :  Annuler

2025-02-10 21:27 UTC, pilasou commented on src/assets/i18n/fr.json5
> +
Can be translated by : Une erreur s'est produite lors de la suppression du processus

2025-02-10 21:28 UTC, pilasou commented on src/assets/i18n/fr.json5
> +  "process.detail.delete.header": "",
Can be translated by : Supprimer un processus

2025-02-10 21:29 UTC, pilasou commented on src/assets/i18n/fr.json5
> +
Change for: Le processus a bien été supprimé.

2025-02-10 21:30 UTC, pilasou commented on src/assets/i18n/fr.json5
> +  "process.detail.refreshing": "",
Can be translated by : Actualisation automatique...

2025-02-10 21:31 UTC, pilasou requested changes
Some minor changes should be made before approval. I have indicated them below each tag. Thanks @Peredwel

2025-02-14 15:30 UTC, pilasou approved these changes
Thanks @Peredwel !

2025-02-14 16:28 UTC, tdonohue commented
Thanks @Peredwel !  Merging as this is at +1.  Will try to auto-port to `main` and `dspace-7_x` to get this into 9.0 and 7.6.x.

2025-02-14 16:29 UTC, merged