Prevent request with page size of 9999
DSpace/dspace-angular pull request #3694
Opened 2024-11-26 09:47 UTC by FrancescoMolinaro

## References
Fixes https://github.com/DSpace/dspace-angular/issues/2513

## Description
Correct page size parameter when provided as 9999.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-01-09 14:35 UTC, artlowel requested changes
I don't agree with the approach of using expand to recursively retrieve all pages and still combine them as a single list on the client side. That doesn't solve the issue behind #2513. 

The reason behind #2513 is that we shouldn't ever have a component on the client that requires _all_ data from the server to work. The point of enforcing pagination is to keep the amount of data needed to start using a UI component to a minimum, both because it loads faster, and to reduce strain on the REST server. Getting all pages one at a time before we render something is arguably also slower and less efficient than just requesting everything in a single huge page.

What _would_ solve #2513 imo is to replace all UI components that don't support working with _one_ page at a time with ones that do. E.g. instead of a simple dropdown that contains all values, replace it with an "infinite scroll" style dropdown 

I understand that that may be a lot of work for some of these components, and in other cases the reason why they used a huge page size in the first place was often that there was no rest endpoint to retrieve the exact information we need, so rest endpoints would likely need to be added first. 

If you can't fix every instance in this PR, it's okay to leave some out, and leave #2513 open to be solved in later PRs

I wouldn't, however, replace one way of retrieving all data from the server and doing the processing client side, with another.

2025-01-15 16:07 UTC, FrancescoMolinaro commented
Hi @artlowel , thanks for your feedback!

I totally agree with your point and, following your suggestion, I have tried to improve the logic where possible, either using infinite scrolling or a "load more" button.

The only case where I had no luck to improve the solution is for:

src/app/core/data/relationship-type-data.service.ts

here unfortunately the call is made inside an effect and is not easily repleaceable, I think here we would need to add/extend an endpoint on the rest side as suggested also by a todo that was left for the method:

getRelationshipTypeByLabelAndTypes.

I will look forward to your feedback and thanks again for the review.

2025-01-16 17:28 UTC, artlowel requested changes
Thanks @FrancescoMolinaro!

Most of it looks and works good now. I just have a few more inline comments

2025-01-17 16:42 UTC, FrancescoMolinaro commented on src/app/core/data/bundle-data.service.ts
> +    return this.findAllByItem(item, options, useCachedVersionIfAvailable, reRequestOnStale, ...linksToFollow).pipe(
Hi @artlowel thanks for the catch! 

I though we could have use the limitation for bitstreams in the config  ( I believe is 5 per page ) but is actually not true, that changes case by case, my bad.

I have kept the implementation because I think the method should support anyway the pagination and instead of the previous loop with expand I set the pagination parameter of 9999, I know this goes in the opposite direction of the PR but I agree that, in terms of rendering time, one big call is preferable to n small calls.
The solution, as you mentioned, will have to be a new endpoint that returns all the bitstreams by bundle name. 


In addition to this I have also adapted my changes to the dynamic-list.component.ts as I realized that a "load more" button was not the right approach.
The issue that I noticed was happening in case the user would select an option out of range, save the submission, then reload the page; in this case the user would have had to load all options before being able to see his own selection.

The new solution I adopted is to keep the paginated calls, render the first ones as soon as they are ready, then keep loading the next ones in the background, adding them to the view progressively.

I will look forward to your feedback and thanks again!

2025-01-21 11:59 UTC, artlowel commented on src/app/core/data/bundle-data.service.ts
> +    return this.findAllByItem(item, options, useCachedVersionIfAvailable, reRequestOnStale, ...linksToFollow).pipe(
Hi @FrancescoMolinaro 

I can't seem to find a submission config that actually ends up using `dynamic-list.component.ts`. 

Before I tested it by simply replacing the tag component with the list component [here](https://github.com/DSpace/dspace-angular/blob/3029802ad4169af6637c6b1d3bb83c9ca1ab3767/src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-map-fn.ts#L93), and checking the subject field. However that keeps loading infinitely for me now. That might be due to differences between tags and lists tough.

Could you please let me know the backend submission field config you're using test it?

2025-01-21 12:08 UTC, FrancescoMolinaro commented on src/app/core/data/bundle-data.service.ts
> +    return this.findAllByItem(item, options, useCachedVersionIfAvailable, reRequestOnStale, ...linksToFollow).pipe(
Hi @artlowel , to visualize a dynamic-list in the submission form I am using a configuration like the following:

` <field>
          <dc-schema>dc</dc-schema>
          <dc-element>identifier</dc-element>
          <label>Identifiers</label>
          <input-type value-pairs-name="common_identifiers">list</input-type>
          <repeatable>true</repeatable>
          <required />
          <hint>Test hint</hint>
  </field>`
  
The needed part is an input type of  value "list" and a vocabulary, then we have two possible list based on the "repeatable" parameter.
Let me know in case this shouldn't work.

2025-01-23 10:09 UTC, artlowel commented on src/app/core/data/bundle-data.service.ts
> +    return this.findAllByItem(item, options, useCachedVersionIfAvailable, reRequestOnStale, ...linksToFollow).pipe(
Thanks, that config works.

I'd still remove the line break between the pages. 

![image](https://github.com/user-attachments/assets/9f3c17c6-fb91-4021-beac-179cf16bf380)
(In this screenshot I reduced the page size to 2, to get a better idea how pagination works)

After they've loaded it doesn't matter for the user where the page breaks were:

2025-01-23 14:04 UTC, FrancescoMolinaro commented on src/app/core/data/bundle-data.service.ts
> +    return this.findAllByItem(item, options, useCachedVersionIfAvailable, reRequestOnStale, ...linksToFollow).pipe(
Hi @artlowel , thanks again for the feedback, I have removed  the br, I agree it would just weirdly separate the options.

2025-01-23 14:23 UTC, artlowel approved these changes
Thanks @FrancescoMolinaro!

2025-01-23 18:19 UTC, tdonohue approved these changes
👍 Thanks @FrancescoMolinaro !  I tested this today, including testing all the modified components, and I couldn't find any obvious bugs.  I also noticed (in some cases) where scrolling the dropdown loaded the next page, etc. 

This appears to be working well to me.  If any later issues are found, we can solve them in follow-up PRs.

2025-01-23 18:26 UTC, merged

2025-01-23 19:48 UTC, tdonohue commented
@FrancescoMolinaro : I was able to easily port this to `dspace-8_x` in #3887.   However, porting it to `dspace-7_x` appears to be much more complex (I'm seeing a large number of merge conflicts).

Would you be able to create a separate PR to port this to `dspace-7_x`?  I'd gladly test it myself if you can create the port.

2025-01-29 22:46 UTC, tdonohue commented
@FrancescoMolinaro : Just a reminder that we need to still port this PR to `dspace-7_x`.  Please let me know if you'd be able to do that.

2025-01-30 11:36 UTC, FrancescoMolinaro commented
Hi @tdonohue , sorry for the delay, I have opened the backporting PR here https://github.com/DSpace/dspace-angular/pull/3925

2025-08-13 19:35 UTC, pkmcnc commented
Hi!
I observe this problem in 9.1
Shouldn't it be fixed already?
Thank you