Task/dspace 8 x/duracom 303
DSpace/dspace-angular pull request #3709
Opened 2024-12-02 12:24 UTC by FrancescoMolinaro

## References
Fixes https://github.com/DSpace/dspace-angular/issues/3231

## Description

Prevent rendering of search and browse by components in SSR, to avoid long loading period.
Implemented skeleton loader to prevent UI shifting.

## Instructions for Reviewers
 - Search/Browse by component not rendered in SSR and faster response for page loading.
 - No page shifting happening during loading time (only available for search component)

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-01-09 14:29 UTC, ybnd requested changes
Thank you for tackling this!

Looked mostly at the search page so far, since it has the most going on.

> ...faster response for page loading

SSR timings are significantly better with this PR ✅
- With local REST instance: ~0.78s → ~0.60ms
- With demo REST instance: ~2.3s → ~1.3s


> No page shifting happening during loading time

https://github.com/user-attachments/assets/5f9d6ffa-dd56-4d85-b1ab-8a6d1c03b6f1

- There is noticeable "flashing" while the content loads
    - The SSR page shows the skeleton loader
    - The whole page disappears for a fraction of a second and is re-rendered, now with the sort/results section filled in correctly, but still with the skeleton loader
        - This is was already happening and is still happening on 9.0, so could be tackled in a separate PR
    - Then the facet sidebar is filled in with facet data (without fade-in)
    - Finally, the search results load (with fade-in)
        - At the same time, the facet sidebar is updated accordingly, which can cause facets to disappear (again without fade-in)
        - If a filter is applied, the results get pushed down as the badge is loaded in
- It may be less jarring to wait for the final request to resolve before we replace the skeleton and using the same fade-in animation as the search results for the facets
- We know by the URL when at least one filter is applied, so you could include a filter badge placeholder

The skeleton loader looks out of place right now
- The placeholders don't match the style sufficiently
    - Colour is different; should use exact same CSS for background colors of "blocky" bits!
    - Shadows & rounded corners where there are none in the actual theme 
    - Thumbnail size & margin with text content doesn't match
- The grid view uses the same skeleton loader as the list view

After the initial load:
- If you change between the same query/filters, the search request is retrieved quickly from the cache, but the skeleton loader is still shown for a fraction of a second
- It would look smoother if you could avoid this and fade directly from one set of results to the other.

2025-01-09 16:48 UTC, tdonohue requested changes
@FrancescoMolinaro : We briefly discussed this PR in today's Developers Meeting.  As mentioned there, I think this PR needs to be made *configurable*, with an example in `config.example.yml`.  Currently, it appears there's no way to control whether this is enabled or disabled.

Ideally, I'd like to see an option similar to `ssr.enableSearchBrowseComponents: false` or separate `ssr.enableSearchComponent: false` and `ssr.enableBrowseComponent: false` settings.   When set to `false`, the components will be excluded from SSR.  When set to `true`, they will still be included in SSR.

I've added a few other minor comments inline below.  I haven't had a chance to test this yet, but will do so soon.

2025-01-09 16:48 UTC, tdonohue commented on src/config/search-page-config.interface.ts
> +   * Number used to render n skeletons while the filters are loading
I'm not sure I understand this description, which means other developers may not.  What are "skeletons" and what do they have to do with "defaultFilterCount"?

Is there a different way we can describe this setting?  Or maybe given an example of what will happen if you set this to 5 or 0 or 10.

2025-01-09 16:48 UTC, tdonohue commented on src/config/default-app-config.ts
> +    defaultFilterCount: 5,
We should add an example of this new setting also to the `config.example.yml` with an explanation of what it does and why you might change it.

2025-01-13 17:06 UTC, FrancescoMolinaro commented
Hi @ybnd ,

Thanks for your review and feedback, much appreciated!

I tried tackling all the open points that you indicated but on some of them I had no luck, in specific:

- Visible flash on page load:

I tried debugging a bit the issue and seems occurring on every page in the hydration phase. 
I believe this is casued by the way we serve/hydrate the pages in SSR and it needs a deep analysis of the issue.
I would handle this issue in a separate PR as could have a very significant impact on App.


- Fade in effect on filters:

This seemed at first a point easily solvable but is more complex than I have anticipated.
On the filters there is already a "Slide in" animation, to open/close the filters, and is not easy to calculate when to process a state or the other as the open/close state is based on Http requests to check the content of the facets.

Adding two additional animations states for the facets, so enter/leave, will result in an unpredictable change of state, therefore a broken animation. I believe could be the reason why the facets don't have already such animation.

The solution imo  is to execute first a "Fade in" animation then calculate which filter is open and which is not, but the result would be a bit mechanic and slow, as we would delay the first possible interaction of the user with the components.


-  Changes between the same query/filters

I have tried to approach this problem but I think is not of easy solution, this because we would need to know which call is cached before the search button is clicked or a filter is selected, as in that moment we perform the call and show the loading.
The only possibility imo is to keep a state/registry of calls peformed on the specific search page, update them on every interaction of the user so that the check is ready in the moment the users clicks, but this could also result in a computational delay, meaning that in a complex state even if we would have all the info before the search happens, it could take some milliseconds before the matching cached request is find, defeating the purpose of the logic.

I think the same goes for every component in the application, as the "...loading" is shown in any case before making a request.
I believe this too could be considered for another PR, if worth the effort.




For the remaining points, I have improved the solution and I will be looking forward to your feedback.
Thank you in advance.

2025-01-17 17:58 UTC, tdonohue requested changes
@FrancescoMolinaro : Thanks for the updates to the code that I requested.  This is looking great now overall.  

I'm seeing two errors though in my testing

**First**, I am seeing a small error/bug in SSR of the browse component.  Here's what I'm doing:
1. I'm running this PR in production mode (`yarn run build:prod; yarn run serve:ssr`) with default settings
2. Turn off Javascript in your browser.
3. Then, visit any browse page. (e.g. http://locahost:4000/browse/title).  This could be global browse or one of the browse by options on Community/Collection pages.
4. When the browse page undergoes SSR, you'll see this error in the SSR logs (probably on the commandline where you ran `yarn run serve:ssr`)
    ```
    ERROR TypeError: Cannot read properties of null (reading 'id')
    at BrowseByComponent2.ngOnChanges (C:\dspace-angular\dist\server\main.js:1:1122969)
    at ThemedBrowseByComponent2.ngOnChanges (C:\dspace-angular\dist\server\main.js:1:2324715)
    at Object.next (C:\dspace-angular\dist\server\main.js:1:2326337)
    at ConsumerObserver2.next (C:\dspace-angular\dist\server\main.js:1:3345756)
    at SafeSubscriber2.Subscriber2._next (C:\dspace-angular\dist\server\main.js:1:3345118)
    at SafeSubscriber2.Subscriber2.next (C:\dspace-angular\dist\server\main.js:1:3344555)
    at C:\dspace-angular\dist\server\main.js:1:3360363
    at OperatorSubscriber2._this._next (C:\dspace-angular\dist\server\main.js:1:3391010)
    at OperatorSubscriber2.Subscriber2.next (C:\dspace-angular\dist\server\main.js:1:3344555)
    at C:\dspace-angular\dist\server\main.js:1:3464251
    ```
5. The error appears to be harmless, but we should fix it nonetheless.

**Second**, if I set `enableBrowseComponent: true`, then I find that some browse by pages do *NOT* go through SSR.
1. Same scenario above, except I've now set `enableBrowseComponent: true`
2. Turn off Javascript in your browser.
3. Visit Browse by Subject (http://localhost:4000/browse/subject).  It works in SSR!
4. Visit Browse by Title (http://localhost:4000/browse/title) or Date (http://localhost:4000/browse/dateissued).  **They do NOT work in SSR**

Overall, though, this looks very good.  I feel the skeleton page feature works well, and while there is a flash, it's not too significant (it's the same flash we currently have).  So, I think it looks good enough for now, and we can always improve upon it later as we find improvements.

2025-01-17 17:58 UTC, tdonohue commented on src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.ts
> +@Component({
Please add some TypeDocs or a comment to describe the purpose of this component.  We require that for all new components.

2025-01-20 12:20 UTC, FrancescoMolinaro commented
Hi @tdonohue many thanks for the feedback!
I have adapted a the components following your comment and both the error and the rendering functionality should be now ok.
For the skeleton component I have added a descriptive commment, I hope is ok.

I will look forward to your review and thanks again!

2025-01-20 15:33 UTC, ybnd requested changes
@FrancescoMolinaro 

Thank you for addressing things so quickly!

Grid views look great, I've added some last suggestions for the list views.

I agree that everything else can be considered out of scope for this PR, I'll open separate issues 👍

2025-01-20 15:33 UTC, ybnd commented on src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.html
> +        <div class="thumbnail-skeleton">
Can you add a `col-3 col-md-2` class here? 
This should ensure that it scales in the same way as all of our `SearchResultListElementComponent` templates

2025-01-20 15:33 UTC, ybnd commented on src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.scss
> +      width: var(--ds-search-skeleton-thumbnail-width);
Can you reuse the existing `--ds-thumbnail-max-width` variable to match "real" thumbnails without having to keep them "in sync"?

Now it seems that the width/height/padding was made to fit, but it only really works for viewports between 1000 and 1200px wide.

2025-01-21 09:54 UTC, FrancescoMolinaro commented on src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.html
> +        <div class="thumbnail-skeleton">
Hi @ybnd , thanks for the feedback, I have refactored the template so that is as close as possible as the SearchResultListElementComponent one, it should be ok now.

2025-01-21 11:04 UTC, ybnd commented on src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.scss
> +      width: var(--ds-search-skeleton-thumbnail-width);
Another option could be to follow the same approach our HTML placeholders use: [assume thumbnails follow the A4 ratio](https://git.atmire.com/contributions/dspace-angular/blob/1f9f250351cbd1fef33065587d7e40a430ddb518/src/app/thumbnail/thumbnail.component.scss#L15-15): `297 / 210`

Tried this out quickly by copying the `.inner > .outer > .thumbnail-placeholder` HTML/CSS to the loader and it does feel a bit closer in size to the final thumbnails...
However, it's also not very effective, since we will _always_ have some vertical shifting in the search results anyway.

→ Agreed to keep it like this ✅

2025-01-21 11:05 UTC, ybnd commented on src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.html
> +        <div class="thumbnail-skeleton">
I can't see any horizontal shifting at all now, looks great 👍

2025-01-21 22:35 UTC, tdonohue approved these changes
👍 Thanks @FrancescoMolinaro !  I've retested & re-reviewed everything today.  All the prior issues are solved.  The minor code updates look good too.

I'll leave this open for a day or two for @ybnd to give it a final look.  But, it looks ready to merge to me!

2025-01-23 16:07 UTC, merged

2025-01-23 16:22 UTC, tdonohue commented
@FrancescoMolinaro : I've manually ported this to `main` in #3886.  

However, the port to `dspace-7_x` seems much more complex, as there's a large number of code conflicts.  Could you possibly port this to `dspace-7_x` in a separate PR, since you know this code well?  I'd be glad to give it a quick test on my end after the port is complete.

2025-02-04 14:59 UTC, tdonohue commented
Because this has been asked several times as to how this PR is related to #3682, I'm copying the explanation from https://github.com/DSpace/dspace-angular/pull/3907#issuecomment-2622334482

> @alanorth : This PR is complementary to https://github.com/DSpace/dspace-angular/pull/3682, but it's not the same thing.

>
>* https://github.com/DSpace/dspace-angular/pull/3682 limits which pages/paths undergo SSR. So, that PR does exclude the >/search and /browse paths/pages from SSR.
> * However, PR https://github.com/DSpace/dspace-angular/pull/3709 _excludes the search and browse Angular components from SSR_. This means that it also excludes embedded search/browse sections in other pages.
>
>One example is that all Communities/Collections have embedded browse tabs. Those tabs are excluded from SSR by https://github.com/DSpace/dspace-angular/pull/3709 because they cannot be excluded from SSR in https://github.com/DSpace/dspace-angular/pull/3682 without excluding the entire community/collection page.

>
>Similarly, some Entities (e.g. Person entities) may have an embedded search section (e.g. to search through all Publications of a Person). That embedded search section is excluded from SSR by https://github.com/DSpace/dspace-angular/pull/3709 because it cannot be excluded from SSR in https://github.com/DSpace/dspace-angular/pull/3682 without excluding the entire entity page.