#10053: Add support for PCI Endorsement workflow
DSpace/dspace-angular pull request #3735
Opened 2024-12-09 16:39 UTC by amgciadev

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes https://github.com/DSpace/DSpace/issues/10053
* Requires DSpace/DSpace#10090

## Description
This PR fixes the issues described in https://github.com/DSpace/DSpace/issues/10053 and provides better support for the PCI Endorsement workflow
## Instructions for Reviewers
List of changes in this PR:
* Modifies the service creation form to add support for the usesActorEmailId parameter (to allow the configuration of the service in cases where the submitter email needs to be sent in the LDN notifications)
* Modifies signposting model to allow exposing the profile attribute in signposting describedBy typed links

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [X] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [X] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [X] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [X] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [X] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [X] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [X] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [X] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [X] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [X] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2024-12-09 17:53 UTC, tdonohue commented
@abollini or @atarix83 : I'm assigning this to you because it's improvements to COAR Notify to support PCI better. Could you or someone on your team take a look at this / test it out?

2025-02-26 16:11 UTC, steph-ieffam commented
Hey @amgciadev just a minor stuff I have noticed while testing. I would suggest to change the label `quality-assurance.event.table.event.message.serviceUrl` from **Service URL** to a more general label **Actor**

I'm asking you this change just because with the recent changes you implemented in that field the email of the submitter will be displayed so it makes sense to have a more general label
In the following screenshot **aaa** is just a random test email I used on my local env.

![Screenshot from 2025-02-26 15-51-22](https://github.com/user-attachments/assets/ea50202f-4c93-48ac-a683-2281bc33fddb)

2025-02-27 13:30 UTC, steph-ieffam requested changes
Hey @amgciadev I check my note https://github.com/DSpace/dspace-angular/pull/3735#issuecomment-2685530460

2025-02-27 13:37 UTC, amgciadev commented
@steph-ieffam  update the label now on this PR and on the dspace 8 port PR

2025-02-27 16:39 UTC, amgciadev commented
@steph-ieffam just mentioning this issue here: DSpace/dspace-angular#4042. I have been testing again the PCI workflows in full (on a 8.1 DSpace instance) to test fixes PCI has put at their end for the resubmission workflow but encountered issues when submitting endorsement requests due to the issue describe above. Do you have any hints on where to look in the angular to track down any changes between 7.x (I think that in 8.0 it was also working as that is what we were using to fix and test what we have put in this PR) and 8.1 where it no longer works.

2025-03-05 07:25 UTC, steph-ieffam commented
Hey @amgciadev thanks for reporting the issue https://github.com/DSpace/dspace-angular/issues/4042 
We're already looking at the issue, as far I understand the issue is not directly impacting the changes in this PR since it's related to the PCI side when they retrieve information using signposting. Can you kindly confirm that?
That said, the changes in this PR looks good so I'm approving your PR

2025-03-05 07:26 UTC, steph-ieffam approved these changes

2025-03-05 07:45 UTC, amgciadev commented
Hi @steph-ieffam , that is correct: PCI uses HEAD requests to retrieve signposting links.

2025-03-17 15:44 UTC, tdonohue approved these changes
👍 Thanks @amgciadev !  Code looks good & was tested already.

2025-03-17 15:44 UTC, merged

2025-03-17 15:46 UTC, tdonohue commented
Ported to 8.x in #4037