browse pages should not ignore sort config from back end
DSpace/dspace-angular pull request #3741
Opened 2024-12-12 09:35 UTC by jensvannerum

## References
* Fixes https://github.com/DSpace/DSpace/issues/8651
* 7.x branch for backport: https://github.com/atmire/dspace-angular/tree/w2p-122064_browse-pages-ignore-sort-config-fix-UI

## Description
Introduces a new service method to obtain the configured sort direction of a browse index which is then used in the relevant browse components to do the initial fetch. Manually changing sort direction on page will override the configuration of course.

## Instructions for Reviewers
In your `dspace.cfg` change some of the default browse indexes by adding a custom sort order to them ("adding `:desc` at the end as they currently default to asc)

- Verify the browse index loads with this sort order applied
- Verify manually changing pagination / sort order still works as intended
- Verify all other browse functionality still works as intended

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-05-13 12:19 UTC, kanasznagyzoltan commented
Set the title as desc in dspace.cfg when browse is opened it is ordered correctly in a a descending order. The other browses seem to be working fine too.

https://github.com/user-attachments/assets/15fa0598-39bc-4b5a-9dd2-f5a075ea4800

2025-07-01 16:34 UTC, kanasznagyzoltan commented
Dear @jensvannerum 
At the time of the testing we have found it is working. Could you resolve the conflicts?
Thank you!

2025-09-18 15:09 UTC, nwoodward commented
Hi @jensvannerum. This PR looks good, and I'd like to review it. Could you resolve the merge conflicts?

2025-09-19 15:11 UTC, nwoodward approved these changes
👍 Thanks @jensvannerum. With this PR I am able to change the sort direction of the browse indices and see it reflected in the pagination options.

2025-10-01 22:05 UTC, tdonohue requested changes
@jensvannerum : I gave this a quick test today to try to move it along (as it's at +1).  While this code **works**, when I watch the requests sent to the backend (REST API) I'm now seeing **two requests**.

For example, I've set this in my dspace.cfg:
```
webui.browse.index.1 = dateissued:item:dateissued:desc
```

Now, if I open up my DevTools and go to "Browse by Issue Date", I'll see two requests sent to the REST API:
```
GET /api/discover/browses/dateissued/items?page=0&size=1&sort=default,ASC
GET /api/discover/browses/dateissued/items?page=0&size=1&sort=default,DESC
```

Notice how the first request is still **wrong**.  It's sending an `ASC` request when I've configured it for `DESC`.  But, it's immediately followed by a `DESC` request which ultimately returns the correct search (and this is what is displayed in the User Interface).

Would it be possible to get rid of the first request here?  Overall, this code works, but it seems wasteful to send two requests when we need just one.

2026-01-21 15:58 UTC, tdonohue commented
@jensvannerum : Any chance that you'll find time to get back to this PR at some point to solve the [outstanding feedback](https://github.com/DSpace/dspace-angular/pull/3741#pullrequestreview-3291298901)?  There are new comments also on the issue ticket #8651 asking for a status update as well.

If you are unable to move this forward, we could also search out a new volunteer.  Thanks!

2026-01-23 09:40 UTC, jensvannerum commented
Hi @tdonohue, I had considered this PR finished so I missed this feedback, sorry about that.

I think the PR does fix the linked issue, the extra you call mention seeing is expected, it's from the data picker component getting the first (asc) and last (desc) date to show the correct ranges of dates, you'll see this doesn't happen on other (non date) browse indices.

The same behavior is also visible on the demo instance

2026-01-26 22:57 UTC, tdonohue approved these changes
👍 Thanks @jensvannerum for revisiting this and explaining the behavior.  On retesting, I see that you're correct and this behavior is the same as current.  I can verify this PR fixes the bug as described. Looks good to me!

2026-01-26 22:58 UTC, merged

2026-01-26 23:02 UTC, tdonohue commented
@jensvannerum : It looks like all the backports failed here, and I see it's because of changes on `main` in these files.  If you find time to create backports, I'd gladly review/merge them.  If not, then we'll just have this fixed in 10.0.

2026-02-18 14:55 UTC, tdonohue commented
@jensvannerum : This bug appears to have been reported again in #5122 and a possible fix for `dspace-9_x` added to #5121. 

Could you find some time to please backport this PR to `dspace-9_x` (at a minimum)?  I'd obviously rather we have the same fix on all affected branches.