Added text and link properties to menu-item.model.ts
DSpace/dspace-angular pull request #3750
Opened 2024-12-16 08:16 UTC by otuoma

## References
* Fixes #3748 

## Description
In strongly typed typescript setups, using the properties 'link' and 'text' on instances of MenuItemModel fails with the following error

```Object literal may only specify known properties, and 'text' does not exist in type 'MenuItemModel'.```

List of changes in this PR:
* Added link and text properties to MenuItemModel only. From other usage examples, an optional 'icon' property may also be required.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

2025-01-06 17:26 UTC, nwoodward approved these changes
👍 Thanks @otuoma! I tested this locally, and with those two optional properties I can define a menu item as in your example. In fact, I wasn't able to compile the frontend without them.

2025-01-06 18:41 UTC, tdonohue commented
@otuoma : Took at look at this myself today, and I think the original code you were using **may have been wrong**.

In https://github.com/DSpace/dspace-angular/issues/3748 you noted you found this bug by using this code:
```
@Component({
  selector: 'ds-navbar',
  styleUrls: ['./navbar.component.scss'],
  templateUrl: './navbar.component.html',
  animations: [slideMobileNav]
})
export class NavbarComponent extends BaseComponent implements OnInit {
  scholarsMenu: MenuSection = {
    id: 'scholars_menu',
    visible: true,
    active: false,
    model: { type: MenuItemType.LINK, disabled: false, text: 'Scholar Profiles', link: '/communities/fb79-513', },
    index: 0,
    shouldPersistOnRouteChange: true,
  };

  ngOnInit() {
    super.ngOnInit();
    this.menuService.addSection(this.menuID, this.scholarsMenu);
  }
}
```

However, I think you have a **bug** in that code.  In order to specify a `MenuItemType.LINK` you MUST use `LinkMenuItemModel` like this:
```
model: { type: MenuItemType.LINK, disabled: false, text: 'Scholar Profiles', link: '/communities/fb79-513', } as LinkMenuItemModel,
```

If you look in the DSpace codebase, that's how `MenuItemType.LINK` is always used.  A few examples:
* https://github.com/DSpace/dspace-angular/blob/main/src/app/home-page/home-page-routes.ts#L21-L25
* https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/item-page-routes.ts#L75-L79

So, I believe this PR is **unnecessary** if you use the code snippet that I've described above.

2025-01-10 17:43 UTC, tdonohue requested changes
@otuoma : Please see my comment above.  I'm not sure this code change is necessary.  Marking this as "Request Changes" until someone has a chance to verify my comment.

2025-01-17 05:52 UTC, otuoma commented
> LinkMenuItemModel

My bad @tdonohue LinkMenuItemModel already has those 2 fields. This was not necessary.


```
export class LinkMenuItemModel implements MenuItemModel {
  type = MenuItemType.LINK;
  disabled: boolean;
  text: string;
  link: string;
  queryParams?: Params | null;
}```

2025-01-17 15:08 UTC, tdonohue commented
@otuoma : Thanks for verifying.

In that case, I'll close this PR along with the original issue.

2025-01-17 15:08 UTC, closed without merging