Item edit page metadatafields suggestion & validation
DSpace/dspace-angular pull request #860
Opened 2020-09-04 10:54 UTC by MarieVerdonck

## References
Works with endpoint created in: https://github.com/DSpace/Rest7Contract/pull/145
Fixes a functionality disabled here: https://github.com/DSpace/dspace-angular/pull/749/commits/09f1b7e01fac6746c373e0497ac9971800ffc8a7

## Description
Metadata field auto complete on the edit item page now works with a new endpoint search, that utilises a search with the metadatafields indexed in discovery so they can be searched quicker. So the autocomplete has been re-implemented and a validator which uses the /metadatafields/search/byFieldName?exactName to check if there is 1 exact match to the user's input.

## Instructions for Reviewers
Can be tested by going to the edit item page > metadata and adding a new metadata field, e.g. http://localhost:4000/items/047556d1-3d01-4c53-bc68-0cee7ad7ed4e/edit/metadata. 
When you start putting in a metadata field it should give you a dropdown of suggestions. When your filled in metadata field is not a valid metadata field; when you go to fill in a value, an error message is shown underneath the metadata input field.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

2020-09-15 21:36 UTC, tdonohue requested changes
@MarieVerdonck : reviewed & tested today.  Overall, this looks great, my only requests are minor...

1. First, I tested this and it works well overall. However, I was surprised that it doesn't stop me from clicking save on an invalid field name.  So, for example, I can type in "dc.titlenotvalid", and I'll see the "Please choose a valid metadata field" error. But, I can still add the field (by clicking the green checkbox) and I can even click the "Save" at the bottom of the page.   The field is NOT added, but I get a success message back as if it all worked.  If I refresh the page the field is gone though.
    * _My expected behavior:_ I'd expect that I should not even be able to add an invalid field.  Maybe the green checkbox should be disabled if you enter something invalid?
2. I have a few minor requests for TypeDocs/comments inline below.

Beyond those two things, this looks good to me!

2020-09-15 21:36 UTC, tdonohue commented on src/app/core/data/metadatafield-response-parsing.service.ts
> +export class MetadatafieldParsingService implements ResponseParsingService {
Please add TypeDocs to describe this service & the `parse()` method below.

2020-09-15 21:36 UTC, tdonohue commented on src/app/core/data/request.models.ts
> +export class GetMetadataFieldRequest extends GetRequest {
Please add TypeDocs (or a brief comment) to describe this new class

2020-09-16 13:30 UTC, MarieVerdonck commented
@tdonohue 
The checkmark is now disabled until the input for the metadata field is now a valid fields, both for new metadata, and editing metadata.

The two places missing docs are actually no longer needed, they were needed in the previous implementation of endpoint to find exact metadatafield match or error if there was no match; (used to used by MetadataFieldDataService#findByExactFieldName) but this is now via the same endpoint /searchByFieldName but with query param exactName, so no longer needed since it just return a paginated list (which can be empty indicating there is no exact match) containing the match, which gets parsed with the existing code. They've now been removed.

2020-09-16 20:13 UTC, tdonohue commented
@MarieVerdonck : Just a quick note. It looks like Travis CI is hitting build errors based on your latest commit.

2020-09-23 21:31 UTC, tdonohue approved these changes
👍 Retested today & it works great now.  Code looks good too.  Thanks @MarieVerdonck !

2020-09-23 21:31 UTC, merged