Tighten security of our Auth Token (JWT) via CSRF prevention techniques
DSpace/dspace-angular pull request #907
Opened 2020-10-19 18:08 UTC by tdonohue

## References
* Requires https://github.com/DSpace/DSpace/pull/3001  (REST PR MUST be merged prior to, or at the same time as this PR)

## Description
This PR makes minor changes to the Angular UI corresponding to the tightened security applied in https://github.com/DSpace/DSpace/pull/3001

Namely, it does the following:
* Updates Logout to send a `POST` request (instead of `GET`), as required by ttps://github.com/DSpace/DSpace/pull/3001
* Ensures a new `X-DSpace-UI` custom header is passed on every request (see new `DSpaceHeaderInterceptor` & corresponding tests).  This new header is used to pass the UI's URL/origin to the backend just in case the `Origin` or `Referer` headers are not sent.  As Angular Universal seems to not send the `Origin` or `Referer` headers, this custom header is primarily for SSR requests (as user browsers tend to send either `Origin` or `Referer` or both).

## Instructions for Reviewers

* Review the code & tests
* Install & run against https://github.com/DSpace/DSpace/pull/3001
    * When run with `yarn start` (AoT compilation), verify that Login succeeds. When in production mode, a Login will trigger SSR during the hard refresh.  So, this Login will not succeed if you ran `main` against  https://github.com/DSpace/DSpace/pull/3001 (as the `X-DSpace-UI` header is required for SSR to use the Auth Token)
    * Also verify Logout still works.  Again, if you ran `main` against ttps://github.com/DSpace/DSpace/pull/3001, then logout would not succeed, as it is currently sent via a `GET` request.
* **WARNING:** End-to-end tests are **EXPECTED TO FAIL** with this PR.  The reason is that e2e testing runs against live backend which is *NOT* currently running  https://github.com/DSpace/DSpace/pull/3001.  This results in CORS policy errors as the `X-DSpace-UI` custom header will be **blocked**.
    * You can see these CORS errors locally by running `yarn run e2e:ci`. They look will look like this: 
    ```
    [1019/123317.621:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://dspace7.4science.cloud/server/api/sites' from origin 'http://localhost:4000' has been blocked by CORS policy: Request header field x-dspace-ui is not allowed by Access-Control-Allow-Headers in preflight response.", source: http://localhost:4000/ (0)
    ```

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
    * **NOTE: e2e tests will FAIL** until https://github.com/DSpace/DSpace/pull/3001 is merged, because this PR relies on a new, (currently untrusted) `X-DSpace-UI` header.
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

2020-10-29 10:46 UTC, atarix83 requested changes
@tdonohue thanks for this PR.

I've installed on a test server with the relative [REST PR](https://github.com/DSpace/DSpace/pull/3001). But it soen't seem to work properly. Indeed even if using hal browser I can login with password and shibboleth, using the angular application I can't login at all.

You can check directly, here links of test installation : 

https://dspace7test.dev01.4science.cloud/home
https://dspace7test.dev01.4science.cloud/server/#/server/api

2020-10-29 14:41 UTC, tdonohue commented
@atarix83 : Thanks for your testing!  I took a look at the demo sites you linked to, and I think there **might** be a configuration issue with the Angular UI (but I'm not 100% certain).  Here's what I see:
* First off, the REST API looks correct.  I can see that it's got `dspace.ui.url` and `dspace.server.url` set properly as the values appear in the `dspaceUI` and `dspaceServer` properties on the homepage: https://dspace7test.dev01.4science.cloud/server/
* However, the Angular UI looks like it may have incorrect configurations. 
    *  If I access https://dspace7test.dev01.4science.cloud/home and try to login, I see that the  new `X-DSpace-UI` header is set to `http://localhost:4001`.  I would expect it to be set to `https://dspace7test.dev01.4science.cloud/`, as that's the full URL of the Angular UI.
* Because of that UI configuration, I suspect this is what I suspect happening:
    * First, I'm assuming you are running the UI in production mode with SSR / Angular Universal enabled.
    * When you login from the UI, a *hard refresh* is triggered. The request will look something like: `https://dspace7test.dev01.4science.cloud/reload/1603981488190?redirect=%2Fhome` in Chrome DevTools
    * That *hard refresh* triggers Angular Universal/SSR (as it's similar to hitting reload in your browser). So, a 'status' request is first made via Angular Universal to the backend. This request should send the `X-DSpace-UI` header.  But, since the value of that header is `http://localhost:4001`, the backend will **block access** to the JWT (as the JWT was generated using an original origin of `https://dspace7test.dev01.4science.cloud/`)
    * Assuming that is occurring, on the backend in the DSpace logs, you'd see a WARNING like: `EPerson [email] at Origin 'http://localhost:4001' tried to reuse a token which is not valid for this Origin or EPerson.`   That warning is telling you that the JWT *exists*, but it was attempted to be reused by a different origin or person (in this case, a different origin).

Overall, I **think** the problem here is that your frontend configuration needs to be something like: 
```
ui: {
  ssl: true
  host: 'dspace7test.dev01.4science.cloud',
  port: 80,
  namespace: '/',
},
```

Essentially, the `X-DSpace-UI` header is set based on the values in your `ui` configuration. And it needs to match the URL set in `dspace.ui.url` on the REST API backend. If I'm misunderstanding your setup let me know.

2020-10-30 18:12 UTC, paulo-graca reviewed
I've tested this interface both with main branch (from commit DSpace 737d3e677ef0c5762a6d70da7298d88fcc3cad80 Date:   Fri Oct 2 10:30:24 2020 -0500 ) and PR DSpace#3001. Using this PR, the Shibboleth authentication works with main branch (the one I've tested) but doesn't work with DSpace#3001. On both, the password authentication works as expected.

2020-10-30 19:11 UTC, tdonohue commented
@paulo-graca : Were there any error messages in the logs or Chrome DevTools that might give a hint as to why Shibboleth wasn't working properly? Did you test logging in via Shibboleth using the HAL Browser as well (with  DSpace/DSpace#3001 installed)?  I'm just trying to see if I can narrow down the issues that are specific to Shibboleth.  Thanks for your testing!

2020-11-04 15:07 UTC, tdonohue commented
@atarix83 : A quick update for you.  With @paulo-graca 's help, I found an issue on the backend with Shibboleth logins from the Angular UI.  Previously, Shibboleth logins worked from the HAL Browser, but didn't work from Angular UI _unless_ you set `jwt.login.token.include.origin = false` on the backend.  I believe that is now fixed (see https://github.com/DSpace/DSpace/pull/3001#issuecomment-721418142).

It is possible this is the issue you were seeing in your initial tests.  So, if you can find time to retest, I'd appreciate it!  Keep in mind though (as [I previously mentioned](https://github.com/DSpace/dspace-angular/pull/907#issuecomment-718798425)) the UI settings in the Angular configs still need to match the `dspace.ui.url` on the backend for everything to work as expected.

2020-12-22 23:08 UTC, tdonohue commented
Closing, replaced by #977.  I've figured out a way to simply enable CSRF Protection in Spring Security with customizations to allow it to work for Shibboleth & cross domain. Therefore, this "tighten security" approach is no longer necessary.

2021-01-04 17:46 UTC, closed without merging